/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Color;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import metier.connector_utilisateur;

/**
 *
 * @author trav1
 */
public class Gestiondesagences extends javax.swing.JFrame {

    /**
     * Creates new form Gestiondesagences
     */
    public Gestiondesagences() {
        initComponents();
        
        jLabel20.setVisible(true);
        jLabel20.setText("Veuillez choisir une fonctiannalité");
        jLabel1.setVisible(false);
        jButton2.setVisible(false);
        jLabel2.setVisible(false);
        jLabel6.setVisible(false);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        jTextField9.setVisible(false);
        jTextField18.setVisible(false);
        jTextField1.setVisible(false);
        jTextField2.setVisible(false);
        jButton1.setVisible(false);
        jTextField3.setVisible(false);
        jTextField4.setVisible(false);
        jLabel12.setVisible(false);
        jButton3.setVisible(false);
        jButton4.setVisible(false);
        jButton5.setVisible(false);
        jButton6.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(250, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(10, 68, 130));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MENU");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 60, 50));

        jLabel9.setBackground(new java.awt.Color(255, 0, 0));
        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Création d'une agence");
        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.setOpaque(true);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 260, 52));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("<-- Retourner");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 80, 20));

        jLabel4.setBackground(new java.awt.Color(255, 0, 0));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Modification d'une agence");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.setOpaque(true);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 260, 52));

        jLabel14.setBackground(new java.awt.Color(255, 0, 0));
        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Suppression d'une agence");
        jLabel14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.setOpaque(true);
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 260, 52));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 260, 430));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(51, 51, 51));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("_");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.setOpaque(true);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 20, 30));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Gestion des comptes bancaires");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, -1));

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("X");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.setOpaque(true);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 20, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 30));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 500, 110));

        jTextField9.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField9MouseClicked(evt);
            }
        });
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 160, -1));

        jTextField18.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField18MouseClicked(evt);
            }
        });
        jPanel4.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 160, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel1.setText("Code");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 56, 86, 21));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setText("Libelé");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 84, 113, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setText("Date création");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 121, 84, 23));

        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jPanel4.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 123, 160, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel10.setText("Ville");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 166, 84, -1));

        jTextField2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });
        jPanel4.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 162, 160, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel11.setText("Adresse");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 206, 84, -1));

        jTextField3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField3MouseClicked(evt);
            }
        });
        jPanel4.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 160, -1));

        jButton1.setBackground(new java.awt.Color(250, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Enregistrer");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 288, -1, -1));

        jButton2.setBackground(new java.awt.Color(250, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("OK");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 60, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel12.setText("Entrer le code de l'agence");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 180, -1));
        jPanel4.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 100, -1));

        jButton3.setBackground(new java.awt.Color(250, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Chercher");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        jButton4.setBackground(new java.awt.Color(250, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Enregistrer");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 100, -1));

        jButton5.setBackground(new java.awt.Color(250, 0, 0));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Supprimer");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 90, -1));

        jButton6.setBackground(new java.awt.Color(250, 0, 0));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("OK");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jPanel4.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 50, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 680, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents
private boolean choix_suppression=false;
    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        if (choix_suppression==false){
            jLabel9.setBackground(new Color(52, 82, 104));
            jLabel4.setBackground(new Color(250, 0, 0));
           
            jLabel14.setBackground(new Color(250, 0, 0));
            jLabel1.setVisible(true);
        jLabel2.setVisible(true);
        jLabel6.setVisible(true);
        jLabel10.setVisible(true);
        jLabel1.setVisible(true);
            jTextField9.setVisible(true);
        jTextField18.setVisible(true);
        jTextField1.setVisible(true);
        jTextField2.setVisible(true);
        jButton1.setVisible(true);
        jTextField3.setVisible(true);
            jLabel20.setVisible(false);
           jLabel11.setVisible(true);
            //jTextField9.setVisible(false);
            jTextField4.setVisible(false);
        jLabel12.setVisible(false);
        jButton3.setVisible(false);
           jButton5.setVisible(false);
            
            //        jTextArea1.setVisible(false);

            //         jScrollPane1.setVisible(false);
            //      jTextArea1.setVisible(false);
            
            
           
            
            jButton6.setVisible(false);
            jTextField18.setVisible(true);
            
            
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        if (choix_suppression==false){
            Menu menu=new Menu();
            menu.setVisible(true);
            menu.pack();
            menu.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        if (choix_suppression==false){
            jLabel4.setBackground(new Color(52, 82, 104));
            
            jLabel14.setBackground(new Color(250,0,0));

            //jLabel6.setBackground(new Color(250,0,0));
            jLabel9.setBackground(new Color(250,0,0));
                
            jTextField4.setVisible(true);
            jButton3.setVisible(true);
            jLabel12.setVisible(true);
            
            
            jLabel1.setVisible(false);
        jButton2.setVisible(false);
        jLabel2.setVisible(false);
        jLabel6.setVisible(false);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        jTextField9.setVisible(false);
        jTextField18.setVisible(false);
        jTextField1.setVisible(false);
        jTextField2.setVisible(false);
        jButton1.setVisible(false);
        jTextField3.setVisible(false);
           jButton5.setVisible(false);
            
            jLabel20.setVisible(false);
            
            jTextField9.setVisible(false);

            //         jScrollPane1.setVisible(false);
            //      jTextArea1.setVisible(false);
            jButton6.setVisible(false);
 
            
            
            jTextField18.setVisible(false);
            
            }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        if (choix_suppression==false){
            jLabel14.setBackground(new Color(52, 82, 104));
            jLabel4.setBackground(new Color(250,0,0));
            //jLabel4.setBackground(new Color(250,0,0));
            //jLabel6.setBackground(new Color(250,0,0));
            jLabel9.setBackground(new Color(250,0,0));
            jTextField9.setVisible(false);
            
                jLabel1.setVisible(false);
        jButton2.setVisible(false);
        jLabel2.setVisible(false);
        jLabel6.setVisible(false);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        jTextField9.setVisible(false);
        jTextField18.setVisible(false);
        jTextField1.setVisible(false);
        jTextField2.setVisible(false);
        jButton1.setVisible(false);
        jTextField3.setVisible(false);
            jButton5.setVisible(true);
            jTextField18.setVisible(false);
            jButton3.setVisible(false);
            jLabel20.setVisible(false);
            jButton6.setVisible(false);
            jTextField4.setVisible(true);
            jLabel12.setVisible(true);
            
            
        }

    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        if (choix_suppression==false){
            this.setState(JFrame.ICONIFIED);
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        if (choix_suppression==false){
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jTextField18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField18MouseClicked
        // TODO add your handling code here:
        if(jTextField18_vide==true){
            jTextField18.setForeground(new java.awt.Color(0,0,0));
            jTextField18.setText("");
            jTextField18_vide=false;
        }
    }//GEN-LAST:event_jTextField18MouseClicked

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed
private boolean jTextfield_vide9=false;
private boolean jTextField18_vide=false;
    private void jTextField9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField9MouseClicked
        // TODO add your handling code here:
        if(jTextfield_vide9==true){
            jTextField9.setForeground(new java.awt.Color(0,0,0));
            jTextField9.setText("");
            jTextfield_vide9=false;
        }
    }//GEN-LAST:event_jTextField9MouseClicked
private int x,y;
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        x=evt.getX();
        y=evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x1=evt.getXOnScreen();
              int y1=evt.getYOnScreen();
              this.setLocation(x1-x, y1-y);  // la nouvelle valeur de x - ll'ancienne valeur de x, meme chose pour y, elle donne l'emplacement fait par la souris.
       
    }//GEN-LAST:event_formMouseDragged
private boolean jTextfield_vide18=false,jTextfield_vide1=false,jTextfield_vide2=false,jTextfield_vide3=false;
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String code=jTextField9.getText();
        if (code.equals("")){
            jTextfield_vide9=true;
            jTextField9.setForeground(Color.RED);
            jTextField9.setText("Veuillez le code");
        }
        String libele=jTextField18.getText();
        if (libele.equals("")){
            jTextField18_vide=true;
            jTextField18.setForeground(Color.RED);
            jTextField18.setText("Veuillez entrer la libelé");
        }
        String date_creation=jTextField1.getText();
        if (date_creation.equals("")){
            jTextfield_vide1=true;
            jTextField1.setForeground(Color.RED);
            jTextField1.setText("Veuillez entrer la date");
        }
        String ville=jTextField2.getText();
        if (ville.equals("")){
            jTextfield_vide2=true;
            jTextField2.setForeground(Color.RED);
            jTextField2.setText("Veuillez entrer la ville");
        }
        String adresse=jTextField3.getText();
        if (adresse.equals("")){
            jTextfield_vide3=true;
            jTextField3.setForeground(Color.RED);
            jTextField3.setText("Veuillez entrer l'adresse");
        }
        if(!code.equals("") && !libele.equals("") && !date_creation.equals("") && !ville.equals("") && !adresse.equals("")){
            code=jTextField9.getText();
            libele=jTextField18.getText();
            date_creation=jTextField1.getText();
            ville=jTextField2.getText();
            adresse=jTextField3.getText();
            connector_utilisateur conn=new connector_utilisateur();
            int c;
            c=this.getStringToInt(code);
            String r = null;
            try {
                r = conn.setAgence(c,libele,date_creation,ville,adresse);
            } catch (SQLException ex) {
                Logger.getLogger(Gestiondesagences.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Gestiondesagences.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (r.equals("succes")){
                jLabel1.setVisible(false);
        jButton2.setVisible(true);
        jLabel2.setVisible(false);
        jLabel6.setVisible(false);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        jTextField9.setVisible(false);
        jTextField18.setVisible(false);
        jTextField1.setVisible(false);
        jTextField2.setVisible(false);
        jButton1.setVisible(false);
        jTextField3.setVisible(false);
                jLabel20.setVisible(true);
                jLabel20.setText("Agence ajouter avec succès!");
                
            }
            if (r.equals("echec")){
                jLabel1.setVisible(false);
        jButton2.setVisible(true);
        jLabel2.setVisible(false);
        jLabel6.setVisible(false);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        jTextField9.setVisible(false);
        jTextField18.setVisible(false);
        jTextField1.setVisible(false);
        jTextField2.setVisible(false);
        jButton1.setVisible(false);
        jTextField3.setVisible(false);
        jLabel20.setVisible(true);
                jLabel20.setText("Agence n'a pas été ajouter!");
            }
       
        }
        
    }//GEN-LAST:event_jButton1MouseClicked
public int getStringToInt(String num){
        int montant=0,puis;
               
        int compteur=0;
        char[] c=num.toCharArray();
        for (char c1 : c){
            compteur++;
        }
       
        int cc=-1;
       compteur--;
        for (char c1:c){
            
                    if (c1=='0') cc=0;
                    if (c1=='1') cc=1;
                    if(c1=='2') cc=2;
                    if (c1=='3') cc=3;
                    if (c1=='4') cc=4;
                    if (c1=='5') cc=5;
                    if(c1=='6') cc=6;
                    if (c1=='7') cc=7;
                    if (c1=='8') cc=8;
                    if (c1=='9') cc=9;
                    if (cc!=-1) {
                        puis=(int) Math.pow(10,compteur);
                        montant+=cc*puis;

                        compteur--;
                    }
                }
             return montant;
    }
    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        // TODO add your handling code here:
        if(jTextfield_vide1==true){
            jTextField1.setForeground(new java.awt.Color(0,0,0));
            jTextField1.setText("");
            jTextfield_vide1=false;
        }
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        // TODO add your handling code here:
        if(jTextfield_vide2==true){
            jTextField2.setForeground(new java.awt.Color(0,0,0));
            jTextField2.setText("");
            jTextfield_vide2=false;
        }
    }//GEN-LAST:event_jTextField2MouseClicked

    private void jTextField3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseClicked
        // TODO add your handling code here:
        if(jTextfield_vide3==true){
            jTextField3.setForeground(new java.awt.Color(0,0,0));
            jTextField3.setText("");
            jTextfield_vide3=false;
        }
    }//GEN-LAST:event_jTextField3MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        jLabel1.setVisible(true);
        jButton2.setVisible(false);
        jLabel2.setVisible(true);
        jLabel6.setVisible(true);
        jLabel10.setVisible(true);
        jLabel11.setVisible(true);
        jTextField9.setVisible(true);
        jTextField18.setVisible(true);
        jTextField1.setVisible(true);
        jTextField2.setVisible(true);
        jButton1.setVisible(true);
        jTextField3.setVisible(false);
        jLabel20.setVisible(false);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        String res=jTextField4.getText();
        int code=this.getStringToInt(res);
        connector_utilisateur conn=new connector_utilisateur();
        String[] tab=new String[5];
        try {
            tab=conn.getInfoAgence(code);
        } catch (SQLException ex) {
            Logger.getLogger(Gestiondesagences.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Gestiondesagences.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTextField4.setVisible(false);
        jLabel12.setVisible(false);
        jButton3.setVisible(false);
        
        jLabel1.setVisible(false);
        jButton2.setVisible(false);
        jLabel2.setVisible(true);
        jLabel6.setVisible(true);
        jLabel10.setVisible(true);
        jLabel11.setVisible(true);
        jTextField9.setVisible(true);
        jTextField18.setVisible(true);
        jTextField1.setVisible(true);
        jTextField2.setVisible(true);
        jButton1.setVisible(false);
        jTextField3.setVisible(false);
        jLabel20.setVisible(true);
        
        jTextField9.setText(tab[0]);
        jTextField18.setText(tab[1]);
        jTextField1.setText(tab[2]);
        jTextField2.setText(tab[3]);
        jTextField3.setText(tab[4]);
        //jButton1.setVisible(true);
        jButton4.setVisible(true);
        jButton6.setVisible(false);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
            String  code1=jTextField9.getText();
          String  libele=jTextField18.getText();
          String  date_creation=jTextField1.getText();
         String   ville=jTextField2.getText();
         String   adresse=jTextField3.getText();
            connector_utilisateur conn=new connector_utilisateur();
            int c;
            c=this.getStringToInt(code1);
            String etat="";
        try {
             etat= conn.setInfoAgence(c,libele,date_creation,ville,adresse);
        } catch (SQLException ex) {
            Logger.getLogger(Gestiondesagences.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Gestiondesagences.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (etat.equals("succes")){
            jLabel1.setVisible(false);
        jButton2.setVisible(true);
        jLabel2.setVisible(false);
        jLabel6.setVisible(false);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        jTextField9.setVisible(false);
        jTextField18.setVisible(false);
        jTextField1.setVisible(false);
        jTextField2.setVisible(false);
        jButton1.setVisible(false);
        jTextField3.setVisible(false);
        jTextField4.setVisible(false);
        jLabel12.setVisible(false);
        jButton3.setVisible(false);
        jButton4.setVisible(false);
        jLabel20.setVisible(true);
        jLabel20.setText("Agence modifiée avec succès!");
        jButton5.setVisible(false);
        }
        else{
            jLabel1.setVisible(false);
        jButton2.setVisible(true);
        jLabel2.setVisible(false);
        jLabel6.setVisible(false);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        jTextField9.setVisible(false);
        jTextField18.setVisible(false);
        jTextField1.setVisible(false);
        jTextField2.setVisible(false);
        jButton1.setVisible(false);
        jTextField3.setVisible(false);
        jTextField4.setVisible(false);
        jLabel12.setVisible(false);
        jButton3.setVisible(false);
        jButton4.setVisible(false);
        jLabel20.setVisible(true);
        jButton5.setVisible(false);
        jLabel20.setText("Agence n'a pas été modifiée!");
        }
        
        
        
        
            
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        String c=jTextField4.getText();
        int code=this.getStringToInt(c);
        connector_utilisateur conn=new connector_utilisateur();
        try {
            c=conn.deleteagency(code);
        } catch (SQLException ex) {
            Logger.getLogger(Gestiondesagences.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Gestiondesagences.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (c.equals("succes")){
            jTextField4.setVisible(false);
            jLabel12.setVisible(false);
            jButton5.setVisible(false);
            jLabel20.setVisible(true);
            jButton6.setVisible(true);
            jLabel20.setText("Agence supprimée avec succès!");
            
        }
        else{
            jTextField4.setVisible(false);
            jLabel12.setVisible(false);
            jButton5.setVisible(false);
            jButton6.setVisible(true);
            jLabel20.setVisible(true);
            jLabel20.setText("Agence n'a pas été supprimer!");
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        jButton6.setVisible(false);
        jLabel20.setVisible(false);
        jButton5.setVisible(true);
        jLabel12.setVisible(true);
        jTextField4.setVisible(true);
    }//GEN-LAST:event_jButton6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestiondesagences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestiondesagences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestiondesagences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestiondesagences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestiondesagences().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
