/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import metier.connector_utilisateur;

/**
 *
 * @author trav1
 */
public class Gestiondesclients extends javax.swing.JFrame {

    /**
     * Creates new form Gestiondesclients
     */
    public Gestiondesclients() {
        initComponents();
        jButton3.setVisible(false);
        jLabel20.setVisible(true);
        jLabel20.setText("Veuillez shoisir une fonctionnalité");
        jLabel21.setVisible(false);
        jTextField9.setVisible(false);
        jLabel22.setVisible(false);
        jTextField10.setVisible(false);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        jLabel16.setVisible(false);
        jLabel17.setVisible(false);
        jLabel18.setVisible(false);
        jLabel19.setVisible(false);
        jTextField1.setVisible(false);
        jTextField2.setVisible(false);
        jTextField3.setVisible(false);
        jTextField4.setVisible(false);
        jTextField5.setVisible(false);
        jTextField6.setVisible(false);
        jTextField7.setVisible(false);
        jTextField8.setVisible(false);
        jButton1.setVisible(false);
        jButton2.setVisible(false);
        jButton4.setVisible(false);
        jLabel24.setVisible(false);
        jLabel23.setVisible(false);
        jTextField11.setVisible(false);
        jLabel25.setVisible(false);
        jTextField12.setVisible(false);
        jLabel10.setVisible(false);
        jLabel26.setVisible(false);
        jTextField13.setVisible(false);
        jLabel27.setVisible(false);
        jTextField14.setVisible(false);
        jLabel28.setVisible(false);
        jTextField15.setVisible(false);
        jLabel29.setVisible(false);
        jTextField16.setVisible(false);
        jLabel30.setVisible(false);
        jTextField17.setVisible(false);
        jButton5.setVisible(false);
        jButton6.setVisible(false);
        jButton7.setVisible(false);
        jButton8.setVisible(false);
        jLabel31.setVisible(false);
        jButton9.setVisible(false);
        
        jLabel32.setVisible(false);
        jTextField18.setVisible(false);
        jButton11.setVisible(false);
        jButton10.setVisible(false);
        jLabel33.setVisible(false);
        jTextField19.setVisible(false);
        jLabel34.setVisible(false);
        jComboBox1.setVisible(false);
        jComboBox1.removeAllItems();
        jComboBox1.addItem("Courant");
        jComboBox1.addItem("Epargne");
        jButton12.setVisible(false);
        jButton13.setVisible(false);
       
    }
private boolean choix_suppression=false;// le choix de la suppression d'un client.
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(940, 460));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(51, 51, 51));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("_");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.setOpaque(true);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 20, 30));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Gestion des comptes bancaires");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, -1));

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("X");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.setOpaque(true);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 20, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 30));

        jPanel2.setBackground(new java.awt.Color(250, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Modification d'un client");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.setOpaque(true);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 260, 52));

        jLabel2.setBackground(new java.awt.Color(255, 0, 0));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Afficher la liste des clients et leurs comptes");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 260, 52));

        jLabel4.setBackground(new java.awt.Color(255, 0, 0));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Création d'un client");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.setOpaque(true);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 260, 52));

        jLabel3.setBackground(new java.awt.Color(10, 68, 130));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MENU");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 60, 50));

        jLabel6.setBackground(new java.awt.Color(255, 0, 0));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Suppression d'un client");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.setOpaque(true);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 260, 52));

        jLabel9.setBackground(new java.awt.Color(255, 0, 0));
        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ajouter un compte à un client");
        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.setOpaque(true);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 260, 52));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("<-- Retourner");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 80, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 260, 430));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel10.setText("CIN");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 56, -1));

        jTextField1.setBorder(jLabel2.getBorder());
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 160, 20));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel11.setText("Nom");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 56, 53, -1));

        jTextField2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });
        jPanel4.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 159, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel12.setText("Prenom");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 94, -1, -1));

        jTextField3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField3MouseClicked(evt);
            }
        });
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 93, 159, -1));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel13.setText("Agence");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 132, -1, -1));

        jTextField4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField4MouseClicked(evt);
            }
        });
        jPanel4.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 131, 159, -1));

        jButton1.setBackground(new java.awt.Color(250, 0, 0));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Importer");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 176, -1, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel14.setOpaque(true);
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 22, 159, 136));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel16.setText("Adresse");
        jLabel16.setToolTipText("");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel17.setText("Ville");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 209, -1, -1));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel18.setText("Telephone");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel19.setText("e-mail");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 285, -1, -1));

        jTextField5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField5MouseClicked(evt);
            }
        });
        jPanel4.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 169, 159, -1));

        jTextField6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField6MouseClicked(evt);
            }
        });
        jPanel4.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 208, 159, -1));

        jTextField7.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField7MouseClicked(evt);
            }
        });
        jPanel4.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 246, 160, -1));

        jTextField8.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField8MouseClicked(evt);
            }
        });
        jPanel4.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 284, 160, -1));

        jButton2.setBackground(new java.awt.Color(250, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Enregistrer");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 370, -1, -1));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 380, 110));

        jButton3.setBackground(new java.awt.Color(250, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("OK");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, -1, -1));

        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel21.setText("Entrer le CIN du client à chercher");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 210, -1));

        jTextField9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField9MouseClicked(evt);
            }
        });
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 140, -1));

        jButton4.setBackground(new java.awt.Color(250, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Chercher");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, -1));

        jLabel22.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel22.setText("CIN");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 18, 56, -1));

        jTextField10.setBorder(jLabel2.getBorder());
        jTextField10.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField10MouseClicked(evt);
            }
        });
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 159, -1));

        jLabel23.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel23.setText("Nom");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 50, 20));
        jPanel4.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 140, -1));

        jLabel24.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 380, 20));

        jLabel25.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel25.setText("Prenom");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 60, 20));
        jPanel4.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 140, -1));

        jLabel26.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel26.setText("Agence");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 50, 20));
        jPanel4.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 160, -1));

        jLabel27.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel27.setText("Adresse");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 60, 20));
        jPanel4.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 140, -1));

        jLabel28.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel28.setText("Ville");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, -1, 20));
        jPanel4.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 140, -1));

        jLabel29.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel29.setText("Telephone");
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 70, 20));
        jPanel4.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 140, -1));

        jLabel30.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel30.setText("e-mail");
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 70, 20));
        jPanel4.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 140, -1));

        jButton5.setBackground(new java.awt.Color(250, 0, 0));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Enregistrer");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, -1, -1));

        jButton6.setBackground(new java.awt.Color(250, 0, 0));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Supprimer");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jPanel4.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, -1, -1));

        jButton7.setBackground(new java.awt.Color(250, 0, 0));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("non");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jPanel4.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 60, -1));

        jButton8.setBackground(new java.awt.Color(250, 0, 0));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("oui");
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jPanel4.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 60, -1));

        jButton9.setBackground(new java.awt.Color(250, 0, 0));
        jButton9.setText("OK");
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        jPanel4.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 50, -1));

        jLabel31.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel31.setText("Entrer le CIN du client à supprimer");
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 210, -1));

        jLabel32.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel32.setText("Entrer le CIN du client");
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 190, -1));

        jTextField18.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField18MouseClicked(evt);
            }
        });
        jPanel4.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 140, -1));

        jButton10.setBackground(new java.awt.Color(250, 0, 0));
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Ajouter");
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });
        jPanel4.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, -1, -1));

        jLabel33.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel33.setText("Solde");
        jPanel4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 130, 20));
        jPanel4.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 150, -1));

        jLabel34.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel34.setText("Type du compte");
        jPanel4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 100, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 80, -1));

        jButton11.setBackground(new java.awt.Color(250, 0, 0));
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Chercher");
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        jPanel4.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, -1, -1));

        jButton12.setBackground(new java.awt.Color(250, 0, 0));
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("OK");
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });
        jPanel4.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 50, -1));

        jButton13.setBackground(new java.awt.Color(250, 0, 0));
        jButton13.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("Annuler");
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });
        jPanel4.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 680, 430));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
      if (choix_suppression==false){
        this.setState(JFrame.ICONIFIED);
      }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
       if (choix_suppression==false){
        System.exit(0);
       }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
      if (choix_suppression==false){
        jLabel1.setBackground(new Color(52, 82, 104));
        jLabel2.setBackground(new Color(250,0,0));
        jLabel4.setBackground(new Color(250,0,0));
        jLabel6.setBackground(new Color(250,0,0));
        jLabel9.setBackground(new Color(250,0,0));
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        jLabel16.setVisible(false);
        jLabel17.setVisible(false);
        jLabel18.setVisible(false);
        jLabel19.setVisible(false);
        jTextField1.setVisible(false);
        jTextField2.setVisible(false);
        jTextField3.setVisible(false);
        jTextField4.setVisible(false);
        jTextField5.setVisible(false);
        jTextField6.setVisible(false);
        jTextField7.setVisible(false);
        jTextField8.setVisible(false);
        jButton1.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
        jLabel20.setVisible(false);
        jTextField9.setText("");
        jLabel21.setVisible(true);
        jTextField9.setVisible(true);
        jButton4.setVisible(true);
        jLabel22.setVisible(false);
        jTextField10.setVisible(false);
        
        //jTextArea1.setVisible(false);
        jLabel24.setVisible(false);
        jLabel23.setVisible(false);
        jTextField11.setVisible(false);
        jLabel25.setVisible(false);
        jTextField12.setVisible(false);
        jLabel10.setVisible(false);
        jLabel26.setVisible(false);
        jTextField13.setVisible(false);
        jLabel27.setVisible(false);
        jTextField14.setVisible(false);
        jLabel28.setVisible(false);
        jTextField15.setVisible(false);
        jLabel29.setVisible(false);
        jTextField16.setVisible(false);
        jLabel30.setVisible(false);
        jTextField17.setVisible(false);
        jButton5.setVisible(false);
         //jScrollPane1.setVisible(false);
        //jTextArea1.setVisible(false);
        jButton6.setVisible(false);
         jButton7.setVisible(false);
        jButton8.setVisible(false);
        jLabel31.setVisible(false);
        jButton9.setVisible(false);
         jLabel32.setVisible(false);
        jTextField18.setVisible(false);
        jButton11.setVisible(false);
        jButton10.setVisible(false);
        jLabel33.setVisible(false);
        jTextField19.setVisible(false);
        jLabel34.setVisible(false);
        jComboBox1.setVisible(false);
        jButton12.setVisible(false);
        jButton13.setVisible(false);
      }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
      if (choix_suppression==false){
        jLabel2.setBackground(new Color(52, 82, 104));
        jLabel1.setBackground(new Color(250,0,0));
        jLabel4.setBackground(new Color(250,0,0));
        jLabel6.setBackground(new Color(250,0,0));
        jLabel9.setBackground(new Color(250,0,0));
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        jLabel16.setVisible(false);
        jLabel17.setVisible(false);
        jLabel18.setVisible(false);
        jLabel19.setVisible(false);
        jTextField1.setVisible(false);
        jTextField2.setVisible(false);
        jTextField3.setVisible(false);
        jTextField4.setVisible(false);
        jTextField5.setVisible(false);
        jTextField6.setVisible(false);
        jTextField7.setVisible(false);
        jTextField8.setVisible(false);
        jButton1.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
        jLabel20.setVisible(false);
        jLabel21.setVisible(false);
        jTextField9.setVisible(false);
        jButton4.setVisible(false);
        jLabel22.setVisible(false);
        jTextField10.setVisible(false);
        //jTextArea1.setVisible(false);
        jLabel24.setVisible(false);
        jLabel23.setVisible(false);
        jTextField11.setVisible(false);
        jLabel25.setVisible(false);
        jTextField12.setVisible(false);
        jLabel10.setVisible(false);
        jLabel26.setVisible(false);
        jTextField13.setVisible(false);
        jLabel27.setVisible(false);
        jTextField14.setVisible(false);
        jLabel28.setVisible(false);
        jTextField15.setVisible(false);
        jLabel29.setVisible(false);
        jTextField16.setVisible(false);
        jLabel30.setVisible(false);
        jTextField17.setVisible(false);
        jButton5.setVisible(false);
//         jScrollPane1.setVisible(false);
  //      jTextArea1.setVisible(false);
        jButton6.setVisible(false);
         jButton7.setVisible(false);
        jButton8.setVisible(false);
        jLabel31.setVisible(false);
        jButton9.setVisible(false);
         jLabel32.setVisible(false);
        jTextField18.setVisible(false);
        jButton11.setVisible(false);
        jButton10.setVisible(false);
        jLabel33.setVisible(false);
        jTextField19.setVisible(false);
        jLabel34.setVisible(false);
        jComboBox1.setVisible(false);
        jButton12.setVisible(false);
        jButton13.setVisible(false);
      }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
      if (choix_suppression==false){
        jLabel4.setBackground(new Color(52, 82, 104));
        jLabel1.setBackground(new Color(250,0,0));
        jLabel2.setBackground(new Color(250,0,0));
        jLabel6.setBackground(new Color(250,0,0));
        jLabel9.setBackground(new Color(250,0,0));
        jLabel10.setVisible(true);
        jLabel11.setVisible(true);
        jLabel12.setVisible(true);
        jLabel13.setVisible(true);
        jLabel14.setVisible(true);
        jLabel16.setVisible(true);
        jLabel17.setVisible(true);
        jLabel18.setVisible(true);
        jLabel19.setVisible(true);
        jTextField1.setVisible(true);
        jTextField2.setVisible(true);
        jTextField3.setVisible(true);
        jTextField4.setVisible(true);
        jTextField5.setVisible(true);
        jTextField6.setVisible(true);
        jTextField7.setVisible(true);
        jTextField8.setVisible(true);
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        jButton3.setVisible(false);
        jLabel20.setVisible(false);
        jLabel21.setVisible(false);
        jTextField9.setVisible(false);
        jButton4.setVisible(false);
        jLabel22.setVisible(true);
        jTextField10.setVisible(false);
       // jTextArea1.setVisible(false);
        jLabel24.setVisible(false);
        jLabel23.setVisible(false);
        jTextField11.setVisible(false);
        jLabel25.setVisible(false);
        jTextField12.setVisible(false);
        jLabel10.setVisible(false);
        jLabel26.setVisible(false);
        jTextField13.setVisible(false);
        jLabel27.setVisible(false);
        jTextField14.setVisible(false);
        jLabel28.setVisible(false);
        jTextField15.setVisible(false);
        jLabel29.setVisible(false);
        jTextField16.setVisible(false);
        jLabel30.setVisible(false);
        jTextField17.setVisible(false);
        jButton5.setVisible(false);
        //jScrollPane1.setVisible(false);
        //jTextArea1.setVisible(false);
        jButton6.setVisible(false);
         jButton7.setVisible(false);
        jButton8.setVisible(false);
        jLabel31.setVisible(false);
        jButton9.setVisible(false);
        jButton12.setVisible(false);
        jButton13.setVisible(false);
        jLabel32.setVisible(false);
        jTextField18.setVisible(false);
      }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x1=evt.getXOnScreen();
              int y1=evt.getYOnScreen();
              this.setLocation(x1-x, y1-y);  // la nouvelle valeur de x - ll'ancienne valeur de x, meme chose pour y, elle donne l'emplacement fait par la souris.
       
    }//GEN-LAST:event_formMouseDragged
int x,y;
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        x=evt.getX();
        y=evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
      if (choix_suppression==false){
        jLabel6.setBackground(new Color(52, 82, 104));
        jLabel1.setBackground(new Color(250,0,0));
        jLabel2.setBackground(new Color(250,0,0));
        jLabel4.setBackground(new Color(250,0,0));
        jLabel9.setBackground(new Color(250,0,0));
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        jLabel16.setVisible(false);
        jLabel17.setVisible(false);
        jLabel18.setVisible(false);
        jLabel19.setVisible(false);
        jTextField1.setVisible(false);
        jTextField2.setVisible(false);
        jTextField3.setVisible(false);
        jTextField4.setVisible(false);
        jTextField5.setVisible(false);
        jTextField6.setVisible(false);
        jTextField7.setVisible(false);
        jTextField8.setVisible(false);
        jButton1.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
        jLabel20.setVisible(false);
        jLabel21.setVisible(false);
        jLabel22.setVisible(false);
        jTextField10.setVisible(false);
        jTextField9.setVisible(false);
        jButton4.setVisible(false);
//        jTextArea1.setVisible(false);
        jLabel24.setVisible(false);
        jLabel23.setVisible(false);
        jTextField11.setVisible(false);
        jLabel25.setVisible(false);
        jTextField12.setVisible(false);
        jLabel10.setVisible(false);
        jLabel26.setVisible(false);
        jTextField13.setVisible(false);
        jLabel27.setVisible(false);
        jTextField14.setVisible(false);
        jLabel28.setVisible(false);
        jTextField15.setVisible(false);
        jLabel29.setVisible(false);
        jTextField16.setVisible(false);
        jLabel30.setVisible(false);
        jTextField17.setVisible(false);
        jButton5.setVisible(false);
        jLabel21.setVisible(false);
        jLabel31.setVisible(true);
        jTextField9.setVisible(true);
        jTextField9.setText("");
        jButton6.setVisible(true);
//         jScrollPane1.setVisible(false);
  //      jTextArea1.setVisible(false);
        jButton7.setVisible(false);
        jButton8.setVisible(false);
        
        jButton9.setVisible(false);
         jLabel32.setVisible(false);
        jTextField18.setVisible(false);
        jButton11.setVisible(false);
        jButton10.setVisible(false);
        jLabel33.setVisible(false);
        jTextField19.setVisible(false);
        jLabel34.setVisible(false);
        jComboBox1.setVisible(false);
        jButton12.setVisible(false);
        jButton13.setVisible(false);
        
      }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
      if (choix_suppression==false){
        jLabel9.setBackground(new Color(52, 82, 104));
        jLabel1.setBackground(new Color(250,0,0));
        jLabel2.setBackground(new Color(250,0,0));
        jLabel4.setBackground(new Color(250,0,0));
        jLabel6.setBackground(new Color(250,0,0));
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        jLabel16.setVisible(false);
        jLabel17.setVisible(false);
        jLabel18.setVisible(false);
        jLabel19.setVisible(false);
        jTextField1.setVisible(false);
        jTextField2.setVisible(false);
        jTextField3.setVisible(false);
        jTextField4.setVisible(false);
        jTextField5.setVisible(false);
        jTextField6.setVisible(false);
        jTextField7.setVisible(false);
        jTextField8.setVisible(false);
        jButton1.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
        jLabel20.setVisible(false);
        jLabel21.setVisible(false);
        jTextField9.setVisible(false);
        jButton4.setVisible(false);
        jLabel22.setVisible(false);
        jTextField10.setVisible(false);
//        jTextArea1.setVisible(false);
        jLabel24.setVisible(false);
        jLabel23.setVisible(false);
        jTextField11.setVisible(false);
        jLabel25.setVisible(false);
        jTextField12.setVisible(false);
        jLabel10.setVisible(false);
        jLabel26.setVisible(false);
        jTextField13.setVisible(false);
        jLabel27.setVisible(false);
        jTextField14.setVisible(false);
        jLabel28.setVisible(false);
        jTextField15.setVisible(false);
        jLabel29.setVisible(false);
        jTextField16.setVisible(false);
        jLabel30.setVisible(false);
        jTextField17.setVisible(false);
        jButton5.setVisible(false);
//         jScrollPane1.setVisible(false);
  //      jTextArea1.setVisible(false);
        jButton6.setVisible(false);
         jButton7.setVisible(false);
        jButton8.setVisible(false);
        jLabel31.setVisible(false);
        jButton9.setVisible(false);
        
         jLabel32.setVisible(true);
        jTextField18.setVisible(true);
        jButton11.setVisible(true);
        jButton10.setVisible(false);
        jLabel33.setVisible(false);
        jTextField19.setVisible(false);
        jLabel34.setVisible(false);
        jComboBox1.setVisible(false);
        jButton12.setVisible(false);
        jButton13.setVisible(false);
      }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        boolean jTextfield_vide=false;
        if (jTextField1.getText().equals("")){
            jTextfield_vide=true;
            jTextField1.setForeground(Color.RED);
            jTextField1.setText("Veuiller entrer le CIN");
            cin_vide=true;
        }
        if (jTextField2.getText().equals("")){
            jTextfield_vide=true;
            jTextField2.setForeground(Color.RED);
            jTextField2.setText("Veuiller entrer le nom");
            nom_vide=true;
        }
        if (jTextField3.getText().equals("")){
            jTextfield_vide=true;
            jTextField3.setForeground(Color.RED);
            jTextField3.setText("Veuiller entrer le Prenom");
            prenom_vide=true;
        }
        if (jTextField4.getText().equals("")){
            jTextfield_vide=true;
            jTextField4.setForeground(Color.RED);
            jTextField4.setText("Veuiller entrer l'agence");
            agence_vide=true;
        }
        if (jTextField5.getText().equals("")){
            jTextfield_vide=true;
            jTextField5.setForeground(Color.RED);
            jTextField5.setText("Veuiller entrer l'adresse");
            adresse_vide=true;
            
        }
        if (jTextField6.getText().equals("")){
            jTextfield_vide=true;
            jTextField6.setForeground(Color.RED);
            jTextField6.setText("Veuiller entrer la ville");
            ville_vide=true;
        }
        if (jTextField7.getText().equals("")){
            jTextfield_vide=true;
            jTextField7.setForeground(Color.RED);
            jTextField7.setText("Veuiller entrer le tel");
            telephone_vide=true;
        }
        if (jTextField8.getText().equals("")){
            jTextfield_vide=true;
            jTextField8.setForeground(Color.RED);
            jTextField8.setText("Veuiller entrer l'e-mail");
            email_vide=true;
        }
        if (jTextfield_vide==false){
            String[] str=new String[8];
            str[0]=jTextField1.getText();
            str[1]=jTextField2.getText();
            str[2]=jTextField3.getText();
            str[3]=jTextField4.getText();
            str[4]=jTextField5.getText();
            str[5]=jTextField6.getText();
            str[6]=jTextField7.getText();
            str[7]=jTextField8.getText();
            connector_utilisateur c=new connector_utilisateur();
            String etat=null;
            try {
                etat=c.setClient(str);
            } catch (SQLException ex) {
                Logger.getLogger(Gestiondesclients.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Gestiondesclients.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(etat.equals("succes")){
                 jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        jLabel16.setVisible(false);
        jLabel17.setVisible(false);
        jLabel18.setVisible(false);
        jLabel19.setVisible(false);
        jTextField1.setVisible(false);
        jTextField2.setVisible(false);
        jTextField3.setVisible(false);
        jTextField4.setVisible(false);
        jTextField5.setVisible(false);
        jTextField6.setVisible(false);
        jTextField7.setVisible(false);
        jTextField8.setVisible(false);
        jButton1.setVisible(false);
        jButton2.setVisible(false);
        jLabel21.setVisible(false);
        jTextField9.setVisible(false);
        jButton4.setVisible(false);
        jLabel22.setVisible(false);
        jTextField10.setVisible(false);
//        jTextArea1.setVisible(false);
        jLabel24.setVisible(false);
        jLabel23.setVisible(false);
        jTextField11.setVisible(false);
        jLabel25.setVisible(false);
        jTextField12.setVisible(false);
        jLabel10.setVisible(false);
        jLabel26.setVisible(false);
        jTextField13.setVisible(false);
        jLabel27.setVisible(false);
        jTextField14.setVisible(false);
        jLabel28.setVisible(false);
        jTextField15.setVisible(false);
        jLabel29.setVisible(false);
        jTextField16.setVisible(false);
        jLabel30.setVisible(false);
        jButton5.setVisible(false);
        jTextField17.setVisible(false);
//         jScrollPane1.setVisible(false);
  //      jTextArea1.setVisible(false);
        jButton3.setVisible(true);
        jLabel20.setVisible(true);
        jLabel20.setText("Client enregistrer avec succes!!!");
        jButton6.setVisible(false);
         jButton7.setVisible(false);
        jButton8.setVisible(false);
         jLabel32.setVisible(false);
        jTextField18.setVisible(false);
        jButton11.setVisible(false);
        jButton10.setVisible(false);
        jLabel33.setVisible(false);
        jTextField19.setVisible(false);
        jLabel34.setVisible(false);
        jComboBox1.setVisible(false);
        jButton12.setVisible(false);
        jButton13.setVisible(false);
            }
        }
        
    }//GEN-LAST:event_jButton2MouseClicked
boolean nom_vide=false,cin_vide=false,prenom_vide=false,agence_vide=false,adresse_vide=false,ville_vide=false,telephone_vide=false,email_vide=false;
    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        // TODO add your handling code here:
        if (cin_vide==true){  // si l'utilisateur n'a rien ecrit.
            jTextField1.setForeground(new java.awt.Color(0,0,0));
            jTextField1.setText("");
            cin_vide=false;
        }
        
          
           
             
               
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jTextField8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField8MouseClicked
        // TODO add your handling code here:
        if (email_vide==true){  // si l'utilisateur n'a rien ecrit.
            jTextField8.setForeground(new java.awt.Color(0,0,0));
            jTextField8.setText("");
            email_vide=false;
        }
    }//GEN-LAST:event_jTextField8MouseClicked

    private void jTextField7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField7MouseClicked
        // TODO add your handling code here:
         if (telephone_vide==true){  // si l'utilisateur n'a rien ecrit.
            jTextField7.setForeground(new java.awt.Color(0,0,0));
            jTextField7.setText("");
            telephone_vide=false;
        }
    }//GEN-LAST:event_jTextField7MouseClicked

    private void jTextField6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField6MouseClicked
        // TODO add your handling code here:
        if (ville_vide==true){  // si l'utilisateur n'a rien ecrit.
            jTextField6.setForeground(new java.awt.Color(0,0,0));
            jTextField6.setText("");
           ville_vide=false;
        }
    }//GEN-LAST:event_jTextField6MouseClicked

    private void jTextField5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField5MouseClicked
        // TODO add your handling code here:
         if (adresse_vide==true){  // si l'utilisateur n'a rien ecrit.
            jTextField5.setForeground(new java.awt.Color(0,0,0));
            jTextField5.setText("");
            adresse_vide=false;
        }
             
    }//GEN-LAST:event_jTextField5MouseClicked

    private void jTextField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseClicked
        // TODO add your handling code here:
         if (agence_vide==true){  // si l'utilisateur n'a rien ecrit.
            jTextField4.setForeground(new java.awt.Color(0,0,0));
            jTextField4.setText("");
            agence_vide=false;
        }
    }//GEN-LAST:event_jTextField4MouseClicked

    private void jTextField3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseClicked
        // TODO add your handling code here:
        if (prenom_vide==true){  // si l'utilisateur n'a rien ecrit.
            jTextField3.setForeground(new java.awt.Color(0,0,0));
            jTextField3.setText("");
           prenom_vide=false;
        }
          
    }//GEN-LAST:event_jTextField3MouseClicked

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        // TODO add your handling code here:
         if (nom_vide==true){  // si l'utilisateur n'a rien ecrit.
            jTextField2.setForeground(new java.awt.Color(0,0,0));
            jTextField2.setText("");
            nom_vide=false;
        }
    }//GEN-LAST:event_jTextField2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        Import impor=new Import();
        impor.setVisible(true);
        impor.pack();
        impor.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
      if (choix_suppression==false){
        Menu menu=new Menu();
        menu.setVisible(true);
        menu.pack();
        menu.setLocationRelativeTo(null);
        this.dispose();
      }
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        jLabel10.setVisible(true);
        jLabel11.setVisible(true);
        jLabel12.setVisible(true);
        jLabel13.setVisible(true);
        jLabel14.setVisible(true);
        jLabel16.setVisible(true);
        jLabel17.setVisible(true);
        jLabel18.setVisible(true);
        jLabel19.setVisible(true);
        jTextField1.setVisible(true);
        jTextField1.setText("");
        jTextField2.setVisible(true);
        jTextField2.setText("");
        jTextField3.setVisible(true);
        jTextField3.setText("");
        jTextField4.setVisible(true);
        jTextField4.setText("");
        jTextField5.setVisible(true);
        jTextField5.setText("");     // j'affecte une chaine vide au JTextField pour le vider.
        jTextField6.setVisible(true);
        jTextField6.setText("");
        jTextField7.setVisible(true);
        jTextField7.setText("");
        jTextField8.setVisible(true);
        jTextField8.setText("");
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        jButton3.setVisible(false);
        jLabel20.setVisible(false);
        jLabel21.setVisible(false);
        jTextField9.setVisible(false);
        jButton4.setVisible(false);
        jLabel22.setVisible(false);
        jTextField10.setVisible(false);
//        jTextArea1.setVisible(false);
        jLabel24.setVisible(false);
        jLabel23.setVisible(false);
        jTextField11.setVisible(false);
        jLabel25.setVisible(false);
        jTextField12.setVisible(false);
        jLabel10.setVisible(false);
        jLabel26.setVisible(false);
        jTextField13.setVisible(false);
        jLabel27.setVisible(false);
        jTextField14.setVisible(false);
        jLabel28.setVisible(false);
        jTextField15.setVisible(false);
        jLabel29.setVisible(false);
        jTextField16.setVisible(false);
        jLabel30.setVisible(false);
        jTextField17.setVisible(false);
        jButton5.setVisible(false);
//         jScrollPane1.setVisible(false);
  //      jTextArea1.setVisible(false);
        jButton6.setVisible(false);
         jButton7.setVisible(false);
        jButton8.setVisible(false);
         jLabel32.setVisible(false);
        jTextField18.setVisible(false);
        jButton11.setVisible(false);
        jButton10.setVisible(false);
        jLabel33.setVisible(false);
        jTextField19.setVisible(false);
        jLabel34.setVisible(false);
        jComboBox1.setVisible(false);
        jButton12.setVisible(false);
        jButton13.setVisible(false);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10MouseClicked

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed
boolean jTextfield_vide9=false;
    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        jButton5.setVisible(false);
        jButton6.setVisible(false);
         jButton7.setVisible(false);
        jButton8.setVisible(false);
        String Cin=jTextField9.getText();
        if (Cin.equals("")){
            jTextfield_vide9=true;
            jTextField9.setForeground(Color.RED);
            jTextField9.setText("Veuiller entrer un CIN");
        }
        else {
//            jTextArea1.setVisible(true);
  //      jScrollPane1.setVisible(true);
            jLabel24.setVisible(true);
        jLabel23.setVisible(true);
        jTextField11.setVisible(true);
        jLabel25.setVisible(true);
        jTextField12.setVisible(true);
        jLabel10.setVisible(true);
        jLabel26.setVisible(true);
        jTextField13.setVisible(true);
        jLabel27.setVisible(true);
        jTextField14.setVisible(true);
        jLabel28.setVisible(true);
        jTextField15.setVisible(true);
        jLabel29.setVisible(true);
        jTextField16.setVisible(true);
        jLabel30.setVisible(true);
        jTextField17.setVisible(true);
        jTextField10.setVisible(true);
        connector_utilisateur c=new connector_utilisateur();
        String[] str=new String[9];
        try {
           str=c.getClientInfos(Cin);
        } catch (SQLException ex) {
            Logger.getLogger(Gestiondesclients.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Gestiondesclients.class.getName()).log(Level.SEVERE, null, ex);
        }
    //    jTextArea1.setText(c.toString(str));
        jLabel24.setVisible(true);
        jButton5.setVisible(true);
        jLabel24.setText("Vous pouvez changer les valeurs ici!");
        jTextField11.setText(str[1]);// le nom.
        jTextField12.setText(str[2]); // le prenom.
        jTextField10.setText(str[3]);// le CIN.
        jTextField13.setText(str[8]);// l'agence.
        jTextField14.setText(str[5]);// l'adresse.
        jTextField15.setText(str[4]); // la  ville.
        jTextField16.setText(str[6]);// le  telephone.
        jTextField17.setText(str[7]);// l'email.
    }//GEN-LAST:event_jButton4MouseClicked
    }
    private void jTextField9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField9MouseClicked
        // TODO add your handling code here:
        if(jTextfield_vide9==true){
            jTextField9.setForeground(new java.awt.Color(0,0,0));
            jTextField9.setText("");
            jTextfield_vide9=false;
        }
    }//GEN-LAST:event_jTextField9MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        String str[]=new String[9];
        String cin=jTextField9.getText();
        String etat="";
       str[1]=jTextField11.getText();// le nom.
        str[2]=jTextField12.getText(); // le prenom.
        str[0]=jTextField10.getText();// le CIN.
        str[3]=jTextField13.getText();// l'agence.
        str[4]=jTextField14.getText();// l'adresse.
        str[5]=jTextField15.getText(); // la  ville.
        str[6]=jTextField16.getText();// le  telephone.
        str[7]=jTextField17.getText();// l'email.
        str[8]=cin;//le cin ecrit dans la recherche.
        connector_utilisateur con=new connector_utilisateur();
        try {
            etat=con.setClient(str);
        } catch (SQLException ex) {
            Logger.getLogger(Gestiondesclients.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Gestiondesclients.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (etat.equals("succes")){
//            jTextArea1.setVisible(false);
  //      jScrollPane1.setVisible(false);
            jLabel24.setVisible(false);
        jLabel23.setVisible(false);
        jTextField11.setVisible(false);
        jLabel25.setVisible(false);
        jTextField12.setVisible(false);
        jLabel10.setVisible(false);
        jLabel26.setVisible(false);
        jTextField13.setVisible(false);
        jLabel27.setVisible(false);
        jTextField14.setVisible(false);
        jLabel28.setVisible(false);
        jTextField15.setVisible(false);
        jLabel29.setVisible(false);
        jTextField16.setVisible(false);
        jLabel30.setVisible(false);
        jTextField17.setVisible(false);
        jTextField10.setVisible(false);
        jButton5.setVisible(false);
        jButton3.setVisible(true);
        jLabel20.setVisible(true);
        jLabel20.setText("Client mis-à-jour avec succes!!!");
//         jScrollPane1.setVisible(false);
//        jTextArea1.setVisible(false);
        jButton6.setVisible(false);
         jButton7.setVisible(false);
        jButton8.setVisible(false);
        }
        
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        connector_utilisateur conn=new connector_utilisateur();
        jButton5.setVisible(false);
        String Cin=jTextField9.getText();
        if (Cin.equals("")){
            jTextfield_vide9=true;
            jTextField9.setForeground(Color.RED);
            jTextField9.setText("Veuiller entrer un CIN");
        }
        else{
            String etat_req="";
            try {
                etat_req=conn.getcheckClient(Cin);
            } catch (SQLException ex) {
                Logger.getLogger(Gestiondesclients.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Gestiondesclients.class.getName()).log(Level.SEVERE, null, ex);
            }
          
            
        if (etat_req.equals("found")){
            // si le client existe dans la base de donnees.
                int nbr_comptes=-1;
                try {
                    nbr_comptes=conn.getCheckClientCompte(Cin);
                } catch (SQLException ex) {
                    Logger.getLogger(Gestiondesclients.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Gestiondesclients.class.getName()).log(Level.SEVERE, null, ex);
                }
           if (nbr_comptes==0){ //si le client n'a pas de comptes.
            choix_suppression=true;
            jLabel31.setVisible(false);
            jTextField9.setVisible(false);
            jButton6.setVisible(false);
            jLabel20.setVisible(true);
            jLabel20.setText("Voullez vous vraiment supprimer le client qui a le CIN :  "+Cin);
            jButton7.setVisible(true);
            jButton8.setVisible(true);
           }
           if (nbr_comptes>0){// si le client a plusieurs comptes.
               jLabel20.setVisible(true);
               jLabel20.setText("Vous ne pouvez pas supprimer ce client!");
               jButton9.setVisible(true);
            }
           
          }
        
         if (etat_req.equals("notfound")){  // si le client n'existe pas dans la base de donnees.
            jLabel31.setVisible(false);
            jTextField9.setVisible(false);
            jButton6.setVisible(false);
            jLabel20.setVisible(true);
            jLabel20.setText("Client non trouvé!");
            jButton9.setVisible(true);
            
          }
        }
        
        
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
        String Cin=jTextField9.getText();
        connector_utilisateur conn=new connector_utilisateur();
        String st="";
            try {
                st=conn.deleteClient(Cin);
            } catch (SQLException ex) {
                Logger.getLogger(Gestiondesclients.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Gestiondesclients.class.getName()).log(Level.SEVERE, null, ex);
            }
        if(st.equals("succes")){
            jButton7.setVisible(false);
            jButton8.setVisible(false);
            //jLabel20.setVisible(true);
            jLabel20.setText("Client supprimé avec succès!");
            jButton9.setVisible(true);
        }
        else{
            jButton7.setVisible(false);
            jButton8.setVisible(false);
            //jLabel20.setVisible(true);
            jLabel20.setText("Client non supprimé!");
            jButton9.setVisible(true);
        }
        choix_suppression=false;
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        choix_suppression=false;
        jButton7.setVisible(false);
        jButton8.setVisible(false);
        jLabel20.setText("");
        jLabel20.setVisible(false);
        jLabel31.setVisible(true);
        jTextField9.setVisible(true);
        jButton6.setVisible(true);
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // TODO add your handling code here:
        jLabel20.setText("");
        jLabel20.setVisible(false);
        jButton9.setVisible(false);
        jLabel31.setVisible(true);
        jTextField9.setVisible(true);
        jButton6.setVisible(true);
        
    }//GEN-LAST:event_jButton9MouseClicked
private boolean jTextField18_vide=false;

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        // TODO add your handling code here:
        connector_utilisateur conn=new connector_utilisateur();
        
        String Cin=jTextField18.getText();
        if (Cin.equals("")){
            jTextField18_vide=true;
            jTextField18.setForeground(Color.RED);
            jTextField18.setText("Veuiller entrer un CIN");
        }
        else{
            String etat_req="";
            
            try {
                etat_req=conn.getcheckClient(Cin);
            } catch (SQLException ex) {
                Logger.getLogger(Gestiondesclients.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Gestiondesclients.class.getName()).log(Level.SEVERE, null, ex);
            }
          
            
        if (etat_req.equals("found")){
            // si le client existe dans la base de donnees.
            jLabel20.setVisible(true);
            jLabel20.setText("Entrer les information du compte");
            jLabel33.setVisible(true);
            jTextField19.setVisible(true);
            jLabel34.setVisible(true);
            jComboBox1.setVisible(true);
            jButton10.setVisible(true);
            jLabel32.setVisible(false);
            jTextField18.setVisible(false);
            jButton11.setVisible(false);
            jButton13.setVisible(true);
        }
        
        if (etat_req.equals("notfound")){  // si le client n'existe pas dans la base de donnees.
            jLabel32.setVisible(false);
            jTextField18.setVisible(false);
            jButton11.setVisible(false);
            jLabel20.setVisible(true);
            jLabel20.setText("Client non trouvé!");
            jButton12.setVisible(true);
            
          }
        }
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        // TODO add your handling code here:
        jLabel20.setText("");
        jLabel20.setVisible(false);
        jButton12.setVisible(false);
        jLabel32.setVisible(true);
        jTextField18.setVisible(true);
        jButton11.setVisible(true);
        jButton12.setVisible(false);
        jButton13.setVisible(false);
    }//GEN-LAST:event_jButton12MouseClicked

    private void jTextField18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField18MouseClicked
        // TODO add your handling code here:
        if(jTextField18_vide==true){
            jTextField18.setForeground(new java.awt.Color(0,0,0));
            jTextField18.setText("");
            jTextField18_vide=false;
        }
    }//GEN-LAST:event_jTextField18MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        // TODO add your handling code here:    
        int index_type_compte=jComboBox1.getSelectedIndex();
        String type_compte;
        if (index_type_compte==0) type_compte="Courant";
        else type_compte="Epargne";
        String solde1=jTextField19.getText();
        double solde=0.,puis;
        
        boolean v=false;
        int compteur_avant_vir=0,comp_apres_vir=0,ind=-1,i=0,ind_vir=0;
        char[] c=solde1.toCharArray();
        for (char c1 : c){
            i++;
            if (c1=='.') {
                v=true;
                ind=i;
            }
            if (v==false){
                compteur_avant_vir++;
            }
            else {
                comp_apres_vir++;
            }
        }
        i=0;
        int cc=-1;
        compteur_avant_vir--;
        for (char c1:c){
            i++;
          if (ind!=-1){
            if (i<ind && ind!=-1){
                if (c1=='0') cc=0;
                if (c1=='1') cc=1;
                if(c1=='2') cc=2;
                if (c1=='3') cc=3;
                if (c1=='4') cc=4;
                if (c1=='5') cc=5;
                if(c1=='6') cc=6;
                if (c1=='7') cc=7;
                if (c1=='8') cc=8;
                if (c1=='9') cc=9;
               if (cc!=-1) {
                   puis=Math.pow(10,compteur_avant_vir);
                   solde+=cc*puis;
                   
                   compteur_avant_vir--;
               }
            }
            
            if (i>ind && ind!=-1){
                ind_vir++;
                if (c1=='0') cc=0;
                if (c1=='1') cc=1;
                if(c1=='2') cc=2;
                if (c1=='3') cc=3;
                if (c1=='4') cc=4;
                if (c1=='5') cc=5;
                if(c1=='6') cc=6;
                if (c1=='7') cc=7;
                if (c1=='8') cc=8;
                if (c1=='9') cc=9;
               if (cc!=-1) {
                   puis=Math.pow(10,-(comp_apres_vir-(comp_apres_vir-ind_vir)));
                   solde+=cc*puis;
                   comp_apres_vir--;
               }
        }
          }
          if (ind==-1){
              if (c1=='0') cc=0;
                if (c1=='1') cc=1;
                if(c1=='2') cc=2;
                if (c1=='3') cc=3;
                if (c1=='4') cc=4;
                if (c1=='5') cc=5;
                if(c1=='6') cc=6;
                if (c1=='7') cc=7;
                if (c1=='8') cc=8;
                if (c1=='9') cc=9;
               if (cc!=-1) {
                   
                   puis=Math.pow(10,compteur_avant_vir);
                   solde+=cc*puis;
                  
                   compteur_avant_vir--;
               }
          }
        }
        
        
        connector_utilisateur conn=new connector_utilisateur();
        String CIN=jTextField18.getText();
        System.out.println(CIN);
        int nbr=2;
        try {
            nbr=conn.getCheckClientCompte(CIN);
        } catch (SQLException ex) {
            Logger.getLogger(Gestiondesclients.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Gestiondesclients.class.getName()).log(Level.SEVERE, null, ex);
        }
        String etat="";
        System.out.println(nbr);
        if (nbr<2) {
            try {
                etat=conn.setCompte(solde,type_compte,CIN);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Gestiondesclients.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Gestiondesclients.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (etat.equals("succes")){
                jLabel32.setVisible(false);
                jTextField18.setVisible(false);
                jButton11.setVisible(false);
                jButton10.setVisible(false);
                jButton13.setVisible(false);
                jLabel33.setVisible(false);
                jTextField19.setVisible(false);
                jLabel34.setVisible(false);
                jComboBox1.setVisible(false);
                jLabel20.setVisible(true);
                jLabel20.setText("Compte ajouté avec succès!");
                jButton12.setVisible(true);
            }
            if (etat.equals("echec")){
                jLabel32.setVisible(false);
                jTextField18.setVisible(false);
                jButton11.setVisible(false);
                jButton10.setVisible(false);
                jButton13.setVisible(false);
                jLabel33.setVisible(false);
                jTextField19.setVisible(false);
                jLabel34.setVisible(false);
                jComboBox1.setVisible(false);
                jLabel20.setVisible(true);
                jLabel20.setText("Compte n'a pas été ajouté!");
                jButton12.setVisible(true);
            }
        }
        else{
            jLabel32.setVisible(false);
                jTextField18.setVisible(false);
                jButton11.setVisible(false);
                jButton10.setVisible(false);
                jButton13.setVisible(false);
                jLabel33.setVisible(false);
                jTextField19.setVisible(false);
                jLabel34.setVisible(false);
                jComboBox1.setVisible(false);
                jLabel20.setVisible(true);
                jLabel20.setText("Vous ne pouvez pas ajouter un compte à ce client!");
                jButton12.setVisible(true);
        }
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        // TODO add your handling code here:
        jLabel32.setVisible(true);
        jTextField18.setVisible(true);
        jButton11.setVisible(true);
        jButton10.setVisible(false);
        jLabel33.setVisible(false);
        jTextField19.setVisible(false);
        jLabel34.setVisible(false);
        jComboBox1.setVisible(false);
        jButton12.setVisible(false);
        jButton13.setVisible(false);
        jLabel20.setText("");
        jLabel20.setVisible(false);
    }//GEN-LAST:event_jButton13MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestiondesclients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestiondesclients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestiondesclients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestiondesclients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestiondesclients().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
