/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Color;
import java.sql.SQLException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import metier.CompteCourant;
import metier.connector_utilisateur;

/**
 *
 * @author trav1
 */
public class Gestiondescomptes extends javax.swing.JFrame {

    /**
     * Creates new form Gestiondescomptes
     */
    public Gestiondescomptes() {
        initComponents();
        
        jLabel20.setVisible(true);
        jLabel20.setText("Veuillez shoisir une fonctionnalité");
        jLabel21.setVisible(false);
        jTextField9.setVisible(false);
        jButton3.setVisible(false);
        jLabel11.setVisible(false);
        jLabel10.setVisible(false);
        jTextField2.setVisible(false);
        jLabel12.setVisible(false);
        jTextField3.setVisible(false);
        jLabel13.setVisible(false);
        jTextField4.setVisible(false);
       
        jButton6.setVisible(false);
        jButton7.setVisible(false);
        jButton8.setVisible(false);
        jLabel31.setVisible(false);
        jButton9.setVisible(false);
        jButton13.setVisible(false);
        jLabel32.setVisible(false);
        jTextField18.setVisible(false);
        jButton11.setVisible(false);
        jButton10.setVisible(false);
        jLabel33.setVisible(false);
        jTextField19.setVisible(false);
        jLabel34.setVisible(false);
        jComboBox1.setVisible(false);
        jComboBox1.removeAll();
        jComboBox1.addItem("Courant");
        jComboBox1.addItem("Epargne");
        jButton12.setVisible(false);
        jButton13.setVisible(false);

        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jTextField1.setVisible(false);
        jButton10.setVisible(false);
        jComboBox2.setVisible(false);
            jLabel6.setVisible(false);
        jButton1.setVisible(false);
        jButton4.setVisible(false);
        jLabel16.setVisible(false);
        jButton2.setVisible(false);
        jButton5.setVisible(false);
        
        jLabel18.setVisible(false);
        jScrollPane1.setVisible(false);
        jTable1.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(250, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(10, 68, 130));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MENU");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 60, 50));

        jLabel9.setBackground(new java.awt.Color(255, 0, 0));
        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ajouter un compte à un client");
        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.setOpaque(true);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 260, 52));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("<-- Retourner");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 80, 20));

        jLabel4.setBackground(new java.awt.Color(255, 0, 0));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Réaliser une transaction");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.setOpaque(true);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 260, 52));

        jLabel14.setBackground(new java.awt.Color(255, 0, 0));
        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Suppression d'un compte");
        jLabel14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.setOpaque(true);
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 260, 52));

        jLabel17.setBackground(new java.awt.Color(255, 0, 0));
        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Afficher la liste des transactions");
        jLabel17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel17.setOpaque(true);
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 260, 52));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 260, 430));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(51, 51, 51));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("_");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.setOpaque(true);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 20, 30));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Gestion des comptes bancaires");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, -1));

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("X");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.setOpaque(true);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 20, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 30));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 500, 110));

        jButton3.setBackground(new java.awt.Color(250, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("OK");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, -1, -1));

        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel21.setText("Entrer le CIN du client à chercher");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 210, -1));

        jTextField9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField9MouseClicked(evt);
            }
        });
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 140, -1));

        jButton6.setBackground(new java.awt.Color(250, 0, 0));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Supprimer");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jPanel4.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, -1, -1));

        jButton7.setBackground(new java.awt.Color(250, 0, 0));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("non");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jPanel4.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 60, -1));

        jButton8.setBackground(new java.awt.Color(250, 0, 0));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("oui");
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jPanel4.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 60, -1));

        jButton9.setBackground(new java.awt.Color(250, 0, 0));
        jButton9.setText("OK");
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        jPanel4.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 50, -1));

        jLabel31.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel31.setText("Entrer le CIN du client à supprimer");
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 210, -1));

        jLabel32.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel32.setText("Entrer le CIN du client");
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 190, -1));

        jTextField18.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField18MouseClicked(evt);
            }
        });
        jPanel4.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 140, -1));

        jButton10.setBackground(new java.awt.Color(250, 0, 0));
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Ajouter");
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });
        jPanel4.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, -1, -1));

        jLabel33.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel33.setText("Solde");
        jPanel4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 130, 20));
        jPanel4.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 150, -1));

        jLabel34.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel34.setText("Type du compte");
        jPanel4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 100, 20));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "choix du compte" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jPanel4.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 130, -1));

        jButton11.setBackground(new java.awt.Color(250, 0, 0));
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Chercher");
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        jPanel4.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, -1, -1));

        jButton12.setBackground(new java.awt.Color(250, 0, 0));
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("OK");
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });
        jPanel4.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 50, -1));

        jButton13.setBackground(new java.awt.Color(250, 0, 0));
        jButton13.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("Annuler");
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });
        jPanel4.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, -1, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel1.setText("Découvert autorisé");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 120, -1));

        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel4.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 140, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setText("taux d'intérêt");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 120, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Type de transaction" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jComboBox2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jComboBox2MouseMoved(evt);
            }
        });
        jComboBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox2MouseClicked(evt);
            }
        });
        jPanel4.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 130, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setText("Type de la transaction");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 160, 20));

        jButton1.setBackground(new java.awt.Color(250, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Réaliser");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, -1, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel10.setText("Entrer les CIN des deux clients.");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 280, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel11.setText("Virement de ");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 90, -1));

        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });
        jPanel4.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 90, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel12.setText("à");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 20, 20));

        jTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField3MouseClicked(evt);
            }
        });
        jPanel4.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 90, -1));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel13.setText("Montant");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 90, -1));

        jTextField4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel4.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 100, -1));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel16.setText("Entrer le code du compte");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 170, -1));

        jButton2.setBackground(new java.awt.Color(250, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Valider");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 80, -1));

        jButton4.setBackground(new java.awt.Color(250, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("OK");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 50, -1));

        jButton5.setBackground(new java.awt.Color(250, 0, 0));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Valider");
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 80, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, 230));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel18.setText("La liste des transactions");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 190, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 680, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents
private boolean choix_suppression=false;
    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        if (choix_suppression==false){
            jLabel9.setBackground(new Color(52, 82, 104));
            jLabel4.setBackground(new Color(250, 0, 0));
            jLabel17.setBackground(new Color(250, 0, 0));
            jLabel14.setBackground(new Color(250, 0, 0));
            jTextField1.setVisible(false);
            jLabel2.setVisible(false);

            jButton3.setVisible(false);
            jLabel20.setVisible(false);
            jLabel21.setVisible(false);
            jTextField9.setVisible(false);
            
            jComboBox2.setVisible(false);
            jLabel6.setVisible(false);
            //        jTextArea1.setVisible(false);
           
           
            //         jScrollPane1.setVisible(false);
            //      jTextArea1.setVisible(false);
            jButton6.setVisible(false);
            jButton7.setVisible(false);
            jButton8.setVisible(false);
            jLabel31.setVisible(false);
            jButton9.setVisible(false);

            jLabel32.setVisible(true);
            jTextField18.setVisible(true);
            jButton11.setVisible(true);
            jButton10.setVisible(false);
            jLabel33.setVisible(false);
            jTextField19.setVisible(false);
            jLabel34.setVisible(false);
            jComboBox1.setVisible(false);
            jButton12.setVisible(false);
            jButton13.setVisible(false);
            jButton1.setVisible(false);
             jLabel11.setVisible(false);
        jLabel10.setVisible(false);
        jTextField2.setVisible(false);
        jLabel12.setVisible(false);
        jTextField3.setVisible(false);
        jLabel13.setVisible(false);
        jTextField4.setVisible(false);
       jButton4.setVisible(false);
        jLabel16.setVisible(false);
        jButton2.setVisible(false);
        jButton5.setVisible(false);
        jLabel18.setVisible(false);
        jScrollPane1.setVisible(false);
        jTable1.setVisible(false);
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        if (choix_suppression==false){
            Menu menu=new Menu();
            menu.setVisible(true);
            menu.pack();
            menu.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        if (choix_suppression==false){
            this.setState(JFrame.ICONIFIED);
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        if (choix_suppression==false){
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        // TODO add your handling code here:
        jLabel32.setVisible(true);
        jTextField18.setVisible(true);
        jButton11.setVisible(true);
        jButton10.setVisible(false);
        jLabel33.setVisible(false);
        jTextField19.setVisible(false);
        jLabel34.setVisible(false);
        jComboBox1.setVisible(false);
        jButton12.setVisible(false);
        jButton13.setVisible(false);
        jLabel20.setText("");
        jLabel20.setVisible(false);
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jTextField1.setVisible(false);
        jComboBox2.setVisible(false);
            jLabel6.setVisible(false);
            jButton1.setVisible(false);
             jLabel11.setVisible(false);
        jLabel10.setVisible(false);
        jTextField2.setVisible(false);
        jLabel12.setVisible(false);
        jTextField3.setVisible(false);
        jLabel13.setVisible(false);
        jTextField4.setVisible(false);
       jButton4.setVisible(false);
        jLabel16.setVisible(false);
        jButton2.setVisible(false);
        jButton5.setVisible(false);
        jLabel18.setVisible(false);
        jScrollPane1.setVisible(false);
        jTable1.setVisible(false);
    }//GEN-LAST:event_jButton13MouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        // TODO add your handling code here:
        jLabel20.setText("");
        jLabel20.setVisible(false);
        jButton12.setVisible(false);
        jLabel32.setVisible(true);
        jTextField18.setVisible(true);
        jButton11.setVisible(true);
        jButton12.setVisible(false);
        jButton13.setVisible(false);
        jLabel2.setVisible(false);
        jTextField1.setVisible(false);
        jComboBox2.setVisible(false);
            jLabel6.setVisible(false);
            jButton1.setVisible(false);
             jLabel11.setVisible(false);
        jLabel10.setVisible(false);
        jTextField2.setVisible(false);
        jLabel12.setVisible(false);
        jTextField3.setVisible(false);
        jLabel13.setVisible(false);
        jTextField4.setVisible(false);
       jButton4.setVisible(false);
        jLabel16.setVisible(false);
        jButton2.setVisible(false);
        jButton5.setVisible(false);
        jLabel18.setVisible(false);
        jScrollPane1.setVisible(false);
        jTable1.setVisible(false);
    }//GEN-LAST:event_jButton12MouseClicked
private boolean jTextField18_vide=false;
    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        // TODO add your handling code here:
        jTextField1.setVisible(false);
            jLabel2.setVisible(false);

        connector_utilisateur conn=new connector_utilisateur();

        String Cin=jTextField18.getText();
        if (Cin.equals("")){
            jTextField18_vide=true;
            jTextField18.setForeground(Color.RED);
            jTextField18.setText("Veuiller entrer un CIN");
        }
        else{
            String etat_req="";

            try {
                etat_req=conn.getcheckClient(Cin);
            } catch (SQLException ex) {
                Logger.getLogger(Gestiondesclients.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Gestiondesclients.class.getName()).log(Level.SEVERE, null, ex);
            }

            if (etat_req.equals("found")){
                // si le client existe dans la base de donnees.
                jLabel20.setVisible(true);
                jLabel20.setText("Entrer les information du compte");
                jLabel33.setVisible(true);
                jTextField19.setVisible(true);
                jLabel34.setVisible(true);
                
                jComboBox1.setVisible(true);
                jComboBox1.removeAll();
                jComboBox1.addItem("choix du compte");
                jButton10.setVisible(true);
                jLabel32.setVisible(false);
                jTextField18.setVisible(false);
                jButton11.setVisible(false);
                jButton13.setVisible(true);
            }

            if (etat_req.equals("notfound")){  // si le client n'existe pas dans la base de donnees.
                jLabel32.setVisible(false);
                jTextField18.setVisible(false);
                jButton11.setVisible(false);
                jLabel20.setVisible(true);
                jLabel20.setText("Client non trouvé!");
                jButton12.setVisible(true);

            }
        }
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        // TODO add your handling code here:
        jButton1.setVisible(false);
         jLabel11.setVisible(false);
        jLabel10.setVisible(false);
        jTextField2.setVisible(false);
        jLabel12.setVisible(false);
        jTextField3.setVisible(false);
        jLabel13.setVisible(false);
        jTextField4.setVisible(false);
       jButton4.setVisible(false);
        jLabel16.setVisible(false);
        jButton2.setVisible(false);
        int index_type_compte=jComboBox1.getSelectedIndex();
        String type_compte;
        if (index_type_compte==0) type_compte="Courant";
        else type_compte="Epargne";
        String solde1=jTextField19.getText();
        String dec_taux=jTextField1.getText();
        double solde=getStringToDouble(solde1);
        double decouvert_taux=getStringToDouble(dec_taux);
        
        System.out.println(decouvert_taux+",,,,"+"solde "+solde);
        
        connector_utilisateur conn=new connector_utilisateur();
        String CIN=jTextField18.getText();
        System.out.println(CIN);
        int nbr=2;
        try {
            nbr=conn.getCheckClientCompte(CIN);
        } catch (SQLException ex) {
            Logger.getLogger(Gestiondesclients.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Gestiondesclients.class.getName()).log(Level.SEVERE, null, ex);
        }
        String etat="";
        System.out.println(nbr);
        if (nbr<2) {
            try {
                etat=conn.setCompte1(solde,type_compte,CIN,decouvert_taux);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Gestiondesclients.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Gestiondesclients.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (etat.equals("succes")){
                jLabel32.setVisible(false);
                jTextField18.setVisible(false);
                jButton11.setVisible(false);
                jButton10.setVisible(false);
                jButton13.setVisible(false);
                jLabel33.setVisible(false);
                jTextField19.setVisible(false);
                jLabel34.setVisible(false);
                jComboBox1.setVisible(false);
                jLabel20.setVisible(true);
                jLabel20.setText("Compte ajouté avec succès!");
                jButton12.setVisible(true);
                jTextField1.setVisible(false);
            jLabel2.setVisible(false);
            jLabel1.setVisible(false);

            }
            if (etat.equals("echec")){
                jLabel32.setVisible(false);
                jTextField18.setVisible(false);
                jButton11.setVisible(false);
                jButton10.setVisible(false);
                jButton13.setVisible(false);
                jLabel33.setVisible(false);
                jTextField19.setVisible(false);
                jLabel34.setVisible(false);
                jComboBox1.setVisible(false);
                jLabel20.setVisible(true);
                jLabel20.setText("Compte n'a pas été ajouté!");
                jButton12.setVisible(true);
                jTextField1.setVisible(false);
            jLabel2.setVisible(false);
            jLabel1.setVisible(false);

            }
        }
        else{
            jLabel32.setVisible(false);
            jTextField18.setVisible(false);
            jButton11.setVisible(false);
            jButton10.setVisible(false);
            jButton13.setVisible(false);
            jLabel33.setVisible(false);
            jTextField19.setVisible(false);
            jLabel34.setVisible(false);
            jComboBox1.setVisible(false);
            jLabel20.setVisible(true);
            jLabel20.setText("Vous ne pouvez pas ajouter un compte à ce client!");
            jButton12.setVisible(true);
            jTextField1.setVisible(false);
            jLabel2.setVisible(false);
            jLabel1.setVisible(false);
        }
    }//GEN-LAST:event_jButton10MouseClicked

    private void jTextField18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField18MouseClicked
        // TODO add your handling code here:
        if(jTextField18_vide==true){
            jTextField18.setForeground(new java.awt.Color(0,0,0));
            jTextField18.setText("");
            jTextField18_vide=false;
        }
    }//GEN-LAST:event_jTextField18MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // TODO add your handling code here:
        jLabel20.setText("");
        jLabel20.setVisible(false);
        jButton9.setVisible(false);
        jLabel31.setVisible(false);
        jTextField9.setVisible(false);
        jButton6.setVisible(false);
         jLabel11.setVisible(false);
        jLabel10.setVisible(false);
        jTextField2.setVisible(false);
        jLabel12.setVisible(false);
        jTextField3.setVisible(false);
        jLabel13.setVisible(false);
        jTextField4.setVisible(false);
        jComboBox2.setVisible(true);
            jLabel6.setVisible(true);
            jButton1.setVisible(true);
            
             jLabel11.setVisible(true);
        jLabel10.setVisible(true);
        jTextField2.setVisible(true);
        jLabel12.setVisible(true);
        jTextField3.setVisible(true);
        jLabel13.setVisible(true);
        jTextField4.setVisible(true);
        jButton4.setVisible(false);
        jLabel16.setVisible(false);
        jButton2.setVisible(false);
        jButton5.setVisible(false);
       jLabel18.setVisible(false);
        jScrollPane1.setVisible(false);
        jTable1.setVisible(false);
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
        String Cin=jTextField9.getText();
        connector_utilisateur conn=new connector_utilisateur();
        String st="";
        try {
            st=conn.deleteClient(Cin);
        } catch (SQLException ex) {
            Logger.getLogger(Gestiondesclients.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Gestiondesclients.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(st.equals("succes")){
            jButton7.setVisible(false);
            jButton8.setVisible(false);
            //jLabel20.setVisible(true);
            jLabel20.setText("Client supprimé avec succès!");
            jButton9.setVisible(true);
        }
        else{
            jButton7.setVisible(false);
            jButton8.setVisible(false);
            //jLabel20.setVisible(true);
            jLabel20.setText("Client non supprimé!");
            jButton9.setVisible(true);
        }
        choix_suppression=false;
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        choix_suppression=false;
        jButton7.setVisible(false);
        jButton8.setVisible(false);
        jLabel20.setText("");
        jLabel20.setVisible(false);
        jLabel31.setVisible(true);
        jTextField9.setVisible(true);
        jButton6.setVisible(true);
         jLabel11.setVisible(false);
        jLabel10.setVisible(false);
        jTextField2.setVisible(false);
        jLabel12.setVisible(false);
        jTextField3.setVisible(false);
        jLabel13.setVisible(false);
        jTextField4.setVisible(false);
       jButton4.setVisible(false);
        jLabel16.setVisible(false);
        jButton2.setVisible(false);
        jButton5.setVisible(false);
        jLabel18.setVisible(false);
        jScrollPane1.setVisible(false);
        jTable1.setVisible(false);
    }//GEN-LAST:event_jButton7MouseClicked
private boolean jTextfield_vide9=false;
    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        connector_utilisateur conn=new connector_utilisateur();
        
        String Cin=jTextField9.getText();
        if (Cin.equals("")){
            jTextfield_vide9=true;
            jTextField9.setForeground(Color.RED);
            jTextField9.setText("Veuillez entrer un CIN");
        }
        else{
            String etat_req="";
            try {
                etat_req=conn.getcheckClient(Cin);
            } catch (SQLException ex) {
                Logger.getLogger(Gestiondesclients.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Gestiondesclients.class.getName()).log(Level.SEVERE, null, ex);
            }

            if (etat_req.equals("found")){
                // si le client existe dans la base de donnees.
                int nbr_comptes=-1;
                try {
                    nbr_comptes=conn.getCheckClientCompte(Cin);
                } catch (SQLException ex) {
                    Logger.getLogger(Gestiondesclients.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Gestiondesclients.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (nbr_comptes==0){ //si le client n'a pas de comptes.
                    choix_suppression=true;
                    jLabel31.setVisible(false);
                    jTextField9.setVisible(false);
                    jButton6.setVisible(false);
                    jLabel20.setVisible(true);
                    jLabel20.setText("Voullez vous vraiment supprimer le client qui a le CIN :  "+Cin);
                    jButton7.setVisible(true);
                    jButton8.setVisible(true);
                }
                if (nbr_comptes>0){// si le client a plusieurs comptes.
                    jLabel20.setVisible(true);
                    jLabel20.setText("Vous ne pouvez pas supprimer ce client!");
                    jButton9.setVisible(true);
                }

            }

            if (etat_req.equals("notfound")){  // si le client n'existe pas dans la base de donnees.
                jLabel31.setVisible(false);
                jTextField9.setVisible(false);
                jButton6.setVisible(false);
                jLabel20.setVisible(true);
                jLabel20.setText("Client non trouvé!");
                jButton9.setVisible(true);

            }
        }
    }//GEN-LAST:event_jButton6MouseClicked

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField9MouseClicked
        // TODO add your handling code here:
        if(jTextfield_vide9==true){
            jTextField9.setForeground(new java.awt.Color(0,0,0));
            jTextField9.setText("");
            jTextfield_vide9=false;
        }
    }//GEN-LAST:event_jTextField9MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        
        jTextField1.setVisible(false);
            jLabel2.setVisible(false);

        jButton3.setVisible(false);
        jLabel20.setVisible(false);
        jLabel21.setVisible(false);
        jTextField9.setVisible(false);
        
        //        jTextArea1.setVisible(false);
        
        
        
        //         jScrollPane1.setVisible(false);
        //      jTextArea1.setVisible(false);
        jButton6.setVisible(false);
        jButton7.setVisible(false);
        jButton8.setVisible(false);
        jLabel32.setVisible(false);
        jTextField18.setVisible(false);
        jButton11.setVisible(false);
        jButton10.setVisible(false);
        jLabel33.setVisible(false);
        jTextField19.setVisible(false);
        jLabel34.setVisible(false);
        jComboBox1.setVisible(false);
        jButton12.setVisible(false);
        jButton13.setVisible(false);
        jComboBox2.setVisible(false);
            jLabel6.setVisible(false);
            jButton1.setVisible(false);
             jLabel11.setVisible(false);
        jLabel10.setVisible(false);
        jTextField2.setVisible(false);
        jLabel12.setVisible(false);
        jTextField3.setVisible(false);
        jLabel13.setVisible(false);
        jTextField4.setVisible(false);
       jButton4.setVisible(false);
        jLabel16.setVisible(false);
        jButton2.setVisible(false);
        jButton5.setVisible(false);
        jLabel18.setVisible(false);
        jScrollPane1.setVisible(false);
        jTable1.setVisible(false);
    }//GEN-LAST:event_jButton3MouseClicked
private int x,y;
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        x=evt.getX();
        y=evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x1=evt.getXOnScreen();
              int y1=evt.getYOnScreen();
              this.setLocation(x1-x, y1-y);  // la nouvelle valeur de x - ll'ancienne valeur de x, meme chose pour y, elle donne l'emplacement fait par la souris.
       
    }//GEN-LAST:event_formMouseDragged

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
        
         jComboBox1.removeAllItems();
        jComboBox1.addItem("Courant");
        jComboBox1.addItem("Epargne");
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        int choix=jComboBox1.getSelectedIndex();
        if (choix==0){
            jLabel1.setVisible(true);
            jLabel2.setVisible(false);
            jTextField1.setVisible(true);
            jButton10.setVisible(true);
            jButton13.setVisible(true);
        }
        if (choix==1){
            jLabel1.setVisible(false);
            jLabel2.setVisible(true);
            jTextField1.setVisible(true);
            jButton10.setVisible(true);
            jButton13.setVisible(true);
            
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        if (choix_suppression==false){
            jLabel4.setBackground(new Color(52, 82, 104));
            jLabel17.setBackground(new Color(250, 0, 0));
            jLabel1.setBackground(new Color(250,0,0));
            jLabel14.setBackground(new Color(250,0,0));
            
            //jLabel6.setBackground(new Color(250,0,0));
            jLabel9.setBackground(new Color(250,0,0));
            
            jTextField1.setVisible(false);
            
            jButton3.setVisible(false);
            jLabel20.setVisible(false);
            jLabel21.setVisible(false);
            jTextField9.setVisible(false);
            
            
            //         jScrollPane1.setVisible(false);
            //      jTextArea1.setVisible(false);
            jButton6.setVisible(false);
            jButton7.setVisible(false);
            jButton8.setVisible(false);
            jLabel31.setVisible(false);
            jButton9.setVisible(false);
            jLabel32.setVisible(false);
            jTextField18.setVisible(false);
            jButton11.setVisible(false);
            jButton10.setVisible(false);
            jLabel33.setVisible(false);
            jTextField19.setVisible(false);
            jLabel34.setVisible(false);
            jComboBox1.setVisible(false);
            jButton12.setVisible(false);
            jButton13.setVisible(false);
            jComboBox2.setVisible(true);
            jLabel6.setVisible(true);
            jButton1.setVisible(true);
            
             jLabel11.setVisible(true);
        jLabel10.setVisible(true);
        jTextField2.setVisible(true);
        jLabel12.setVisible(true);
        jTextField3.setVisible(true);
        jLabel13.setVisible(true);
        jTextField4.setVisible(true);
        jButton4.setVisible(false);
        jLabel16.setVisible(false);
        jButton2.setVisible(false);
        jButton5.setVisible(false);
        jLabel18.setVisible(false);
        jScrollPane1.setVisible(false);
        jTable1.setVisible(false);
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jComboBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MouseClicked
        // TODO add your handling code here:
         jComboBox2.removeAllItems();
        jComboBox2.addItem("Dépôt");
        jComboBox2.addItem("Retrait");
    }//GEN-LAST:event_jComboBox2MouseClicked

    public double getStringToDouble(String s){
        double montant=0.,puis;
                boolean v=false;
        int compteur_avant_vir=0,comp_apres_vir=0,ind=-1,i=0,ind_vir=0;
        char[] c=s.toCharArray();
        for (char c1 : c){
            i++;
            if (c1=='.') {
                v=true;
                ind=i;
            }
            if (v==false){
                compteur_avant_vir++;
            }
            else {
                comp_apres_vir++;
            }
        }
        i=0;
        int cc=-1;
        compteur_avant_vir--;
        for (char c1:c){
            i++;
            if (ind!=-1){
                if (i<ind && ind!=-1){
                    if (c1=='0') cc=0;
                    if (c1=='1') cc=1;
                    if(c1=='2') cc=2;
                    if (c1=='3') cc=3;
                    if (c1=='4') cc=4;
                    if (c1=='5') cc=5;
                    if(c1=='6') cc=6;
                    if (c1=='7') cc=7;
                    if (c1=='8') cc=8;
                    if (c1=='9') cc=9;
                    if (cc!=-1) {
                        puis=Math.pow(10,compteur_avant_vir);
                        montant+=cc*puis;

                        compteur_avant_vir--;
                    }
                }

                if (i>ind && ind!=-1){
                    ind_vir++;
                    if (c1=='0') cc=0;
                    if (c1=='1') cc=1;
                    if(c1=='2') cc=2;
                    if (c1=='3') cc=3;
                    if (c1=='4') cc=4;
                    if (c1=='5') cc=5;
                    if(c1=='6') cc=6;
                    if (c1=='7') cc=7;
                    if (c1=='8') cc=8;
                    if (c1=='9') cc=9;
                    if (cc!=-1) {
                        puis=Math.pow(10,-(comp_apres_vir-(comp_apres_vir-ind_vir)));
                        montant+=cc*puis;
                        comp_apres_vir--;
                    }
                }
            }
            if (ind==-1){
                if (c1=='0') cc=0;
                if (c1=='1') cc=1;
                if(c1=='2') cc=2;
                if (c1=='3') cc=3;
                if (c1=='4') cc=4;
                if (c1=='5') cc=5;
                if(c1=='6') cc=6;
                if (c1=='7') cc=7;
                if (c1=='8') cc=8;
                if (c1=='9') cc=9;
                if (cc!=-1) {

                    puis=Math.pow(10,compteur_avant_vir);
                    montant+=cc*puis;

                    compteur_avant_vir--;
                }
            }
        }
              
              return montant;
    }
    
    
    
    
    
    
    
    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here:
        int choix=jComboBox1.getSelectedIndex();
        
    }//GEN-LAST:event_jComboBox2ItemStateChanged
private boolean jTextfield_vide2=false,jTextfield_vide3=false,montant_vide=false;
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        jButton4.setVisible(false);
        jLabel16.setVisible(false);
        jButton2.setVisible(false);
        String cin1,cin2;
        cin1=jTextField2.getText();
        cin2=jTextField3.getText();
        jTextField4.setVisible(true);
        connector_utilisateur conn=new connector_utilisateur();
        if (cin1.equals("")){
            jTextField4.setVisible(true);
            jTextfield_vide2=true;
            jTextField2.setForeground(Color.RED);
            jTextField2.setText("Veuiller entrer un CIN");
      
        }
        if (cin2.equals("")){
            jTextField4.setVisible(true);
            jTextfield_vide3=true;
            jTextField3.setForeground(Color.RED);
            jTextField3.setText("Veuiller entrer un CIN");
           
        }
        
        jTextField4.setVisible(true);
        if (!cin1.equals("") && !cin2.equals("")){
            String etat_req1="",etat_req2="";
            try {
                System.out.println("1");
                etat_req1=conn.getcheckClient(cin1);
            } catch (SQLException ex) {
                Logger.getLogger(Gestiondesclients.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Gestiondesclients.class.getName()).log(Level.SEVERE, null, ex);
            }
          try {
                System.out.println("2");
                etat_req2=conn.getcheckClient(cin2);
            } catch (SQLException ex) {
                Logger.getLogger(Gestiondesclients.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Gestiondesclients.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            
        if (etat_req1.equals("found") && etat_req2.equals("found")){
            // si le client existe dans la base de donnees.
                int nbr_comptes1=-1,nbr_comptes2=-1;
                try {
                    System.out.println("3");
                    nbr_comptes1=conn.getCheckClientCompte(cin1);
                } catch (SQLException ex) {
                    Logger.getLogger(Gestiondesclients.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Gestiondesclients.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    System.out.println("4");
                    nbr_comptes2=conn.getCheckClientCompte(cin2);
                } catch (SQLException ex) {
                    Logger.getLogger(Gestiondesclients.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Gestiondesclients.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
                
           if (nbr_comptes1!=0 && nbr_comptes2!=0){  
               //si les clients ont des comptes.
               String[] compte1,compte2;
               //System.out.println("5");
               compte1=new String[3];
               compte2=new String [3];
               int choix1=-1,choix2=-1;
                int index=jComboBox2.getSelectedIndex(); // 0 pour le depot, 1 pour retrait.
               if (index==0) {
                   choix1=1;
                   choix2=0;
               }
               if (index==1){
                   choix1=0;
                   choix2=1;
               }
                    try {
                        compte1=conn.getCompte1(cin1,choix1);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(Gestiondescomptes.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (SQLException ex) {
                        Logger.getLogger(Gestiondescomptes.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    try {
                        compte2=conn.getCompte1(cin2,choix2);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(Gestiondescomptes.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (SQLException ex) {
                        Logger.getLogger(Gestiondescomptes.class.getName()).log(Level.SEVERE, null, ex);
                    }
               
               double solde1=0,solde2=0,decouvert1=0,decouvert2=0;
               int code1=0,code2=0;
              String montant1=jTextField4.getText();
               solde1=this.getStringToDouble(compte1[0]);
               decouvert1=this.getStringToDouble(compte1[2]);
               solde2=this.getStringToDouble(compte2[0]);
              decouvert2=this.getStringToDouble(compte2[2]);
              
              double montant;
              montant=this.getStringToDouble(montant1);
              
              
              
               CompteCourant c1=new CompteCourant("nom1",solde1,decouvert1);
               CompteCourant c2=new CompteCourant("nom2",solde2,decouvert2);
             
               if (index==0){
                 if (solde1>montant){
                  c1.retirer(montant);
                   c2.deposer(montant);
                
                 
                 
                 
                 //c2.retirer(montant);
                   //c1.deposer(montant);
                   double nouv_solde1,nouv_solde2;
               nouv_solde1=c1.getsolde();
               nouv_solde2=c2.getsolde();
               String etat1 = null,etat2 = null;
                     try {
                         etat1=conn.setCompteSolde(nouv_solde1, cin1);
                     } catch (ClassNotFoundException ex) {
                         Logger.getLogger(Gestiondescomptes.class.getName()).log(Level.SEVERE, null, ex);
                     } catch (SQLException ex) {
                         Logger.getLogger(Gestiondescomptes.class.getName()).log(Level.SEVERE, null, ex);
                     }
                     try {
                         etat2=conn.setCompteSolde(nouv_solde2, cin2);
                     } catch (ClassNotFoundException ex) {
                         Logger.getLogger(Gestiondescomptes.class.getName()).log(Level.SEVERE, null, ex);
                     } catch (SQLException ex) {
                         Logger.getLogger(Gestiondescomptes.class.getName()).log(Level.SEVERE, null, ex);
                     }
               if (etat1.equals("succes") && etat2.equals("succes")){
                   jLabel20.setText("Operation faite avec succès!");
                   jLabel20.setVisible(true);
                   jButton9.setVisible(true);
                   jComboBox2.setVisible(false);
            jLabel6.setVisible(false);
            jButton1.setVisible(false);
            
             jLabel11.setVisible(false);
        jLabel10.setVisible(false);
        jTextField2.setVisible(false);
        jLabel12.setVisible(false);
        jTextField3.setVisible(false);
        jLabel13.setVisible(false);
        jTextField4.setVisible(false);
               }
                 }
            
                 if (solde1<montant){
                     
            jLabel6.setVisible(false);
            jButton1.setVisible(false);
            
             jLabel11.setVisible(false);
        jLabel10.setVisible(false);
        jTextField2.setVisible(false);
        jLabel12.setVisible(false);
        jTextField3.setVisible(false);
        jLabel13.setVisible(false);
        jComboBox2.setVisible(false);
        jTextField4.setVisible(false);
        jLabel20.setText("Le solde n'est pas suffisant!");
                   jLabel20.setVisible(true);
                   jButton9.setVisible(true);
                 }
               }
               if (index==1){
                 if (solde2>montant){
                   c2.retirer(montant);
                   c1.deposer(montant);
                   double nouv_solde1,nouv_solde2;
               nouv_solde1=c1.getsolde();
               nouv_solde2=c2.getsolde();
               String etat1 = null,etat2 = null;
                     try {
                         etat1=conn.setCompteSolde(nouv_solde1, cin1);
                     } catch (ClassNotFoundException ex) {
                         Logger.getLogger(Gestiondescomptes.class.getName()).log(Level.SEVERE, null, ex);
                     } catch (SQLException ex) {
                         Logger.getLogger(Gestiondescomptes.class.getName()).log(Level.SEVERE, null, ex);
                     }
                     try {
                         etat2=conn.setCompteSolde(nouv_solde2, cin2);
                     } catch (ClassNotFoundException ex) {
                         Logger.getLogger(Gestiondescomptes.class.getName()).log(Level.SEVERE, null, ex);
                     } catch (SQLException ex) {
                         Logger.getLogger(Gestiondescomptes.class.getName()).log(Level.SEVERE, null, ex);
                     }
               if (etat1.equals("succes") && etat2.equals("succes")){
                   jLabel20.setText("Operation faite avec succès!");
                   jLabel20.setVisible(true);
                   jButton9.setVisible(true);
                   jComboBox2.setVisible(false);
            jLabel6.setVisible(false);
            jButton1.setVisible(false);
            
             jLabel11.setVisible(false);
        jLabel10.setVisible(false);
        jTextField2.setVisible(false);
        jLabel12.setVisible(false);
        jTextField3.setVisible(false);
        jLabel13.setVisible(false);
        jTextField4.setVisible(false);
               }
                   
               } 
                   
                   
                   
                   
                   
                
                 if (solde2<montant){
                     jComboBox2.setVisible(true);
            jLabel6.setVisible(false);
            jButton1.setVisible(false);
            
             jLabel11.setVisible(false);
        jLabel10.setVisible(false);
        jTextField2.setVisible(false);
        jLabel12.setVisible(false);
        jTextField3.setVisible(false);
        jComboBox1.setVisible(false);
        jLabel13.setVisible(false);
        jTextField4.setVisible(false);
        jLabel20.setText("Le solde n'est pas suffisant!");
                   jLabel20.setVisible(true);
                   jButton9.setVisible(true);
                 }
               }
               
           if (nbr_comptes1==0 && nbr_comptes2==0){
               jLabel1.setVisible(false);
               jLabel10.setVisible(false);
               jLabel12.setVisible(false);
               jLabel11.setVisible(false);
               jTextField2.setVisible(false);
               jTextField3.setVisible(false);
               jLabel13.setVisible(false);
               jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jTextField1.setVisible(false);
        jButton10.setVisible(false);
        jComboBox2.setVisible(false);
            jLabel6.setVisible(false);
        jButton1.setVisible(false);
        jLabel20.setVisible(true);
               jLabel20.setText("Les deux clients n'ont pas de compte!");
               jButton9.setVisible(true);
           }
           if (nbr_comptes1==0 && nbr_comptes2!=0){
               jLabel1.setVisible(false);
               jLabel10.setVisible(false);
               jLabel12.setVisible(false);
               jLabel11.setVisible(false);
               jTextField2.setVisible(false);
               jTextField3.setVisible(false);
               jLabel13.setVisible(false);
               jLabel2.setVisible(false);
        jTextField1.setVisible(false);
        jButton10.setVisible(false);
        jComboBox2.setVisible(false);
            jLabel6.setVisible(false);
        jButton1.setVisible(false);
        jLabel20.setVisible(true);
               jLabel20.setText("Le client qui a le CIN : "+cin1+" n'a pas de compte!");
               jButton9.setVisible(true);
           }
           if (nbr_comptes1!=0 && nbr_comptes2==0){
               jLabel1.setVisible(false);
               jLabel10.setVisible(false);
               jLabel12.setVisible(false);
               jLabel11.setVisible(false);
               jTextField2.setVisible(false);
               jTextField3.setVisible(false);
               jLabel13.setVisible(false);
               jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jTextField1.setVisible(false);
        jButton10.setVisible(false);
        jComboBox2.setVisible(false);
            jLabel6.setVisible(false);
        jButton1.setVisible(false);
        jLabel20.setVisible(true);
               jLabel20.setText(cin2+"Le client qui a le CIN : "+cin2+" n'a pas de compte!");
               jButton9.setVisible(true);
           }
           
          }
        
         if (etat_req1.equals("notfound")){  // si le client n'existe pas dans la base de donnees.
            jLabel1.setVisible(false);
               jLabel10.setVisible(false);
               jLabel12.setVisible(false);
               jLabel11.setVisible(false);
               jTextField2.setVisible(false);
               jTextField3.setVisible(false);
               jLabel13.setVisible(false);
             jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jTextField1.setVisible(false);
        jButton10.setVisible(false);
        jComboBox2.setVisible(false);
            jLabel6.setVisible(false);
        jButton1.setVisible(false);
            jLabel20.setVisible(true);
            jLabel20.setText("Le clientqui a le CIN : "+cin1+" ne figure pas dans la table des clients!");
            jButton9.setVisible(true);
            
          }
         if (etat_req2.equals("notfound")){  // si le client n'existe pas dans la base de donnees.
            jLabel1.setVisible(false);
               jLabel10.setVisible(false);
               jLabel12.setVisible(false);
               jLabel11.setVisible(false);
               jTextField2.setVisible(false);
               jTextField3.setVisible(false);
               jLabel13.setVisible(false);
             jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jTextField1.setVisible(false);
        jButton10.setVisible(false);
        jComboBox2.setVisible(false);
            jLabel6.setVisible(false);
        jButton1.setVisible(false);
            jLabel20.setVisible(true);
            jLabel20.setText("Le clientqui a le CIN : "+cin2+" ne figure pas dans la table des clients!");
            jButton9.setVisible(true);
            
          }
         
         
        }
        
        jTextField4.setVisible(false);
        }   
    }//GEN-LAST:event_jButton1MouseClicked

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        // TODO add your handling code here:
        if(jTextfield_vide2==true){
            jTextField2.setForeground(new java.awt.Color(0,0,0));
            jTextField2.setText("");
            jTextfield_vide2=false;
        }
    }//GEN-LAST:event_jTextField2MouseClicked
    public int getStringToInt(String num){
        int montant=0,puis;
               
        int compteur=0;
        char[] c=num.toCharArray();
        for (char c1 : c){
            compteur++;
        }
       
        int cc=-1;
       compteur--;
        for (char c1:c){
            
                    if (c1=='0') cc=0;
                    if (c1=='1') cc=1;
                    if(c1=='2') cc=2;
                    if (c1=='3') cc=3;
                    if (c1=='4') cc=4;
                    if (c1=='5') cc=5;
                    if(c1=='6') cc=6;
                    if (c1=='7') cc=7;
                    if (c1=='8') cc=8;
                    if (c1=='9') cc=9;
                    if (cc!=-1) {
                        puis=(int) Math.pow(10,compteur);
                        montant+=cc*puis;

                        compteur--;
                    }
                }
             return montant;
    }
    
    
    
    
    
    private void jTextField3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseClicked
        // TODO add your handling code here:
        if(jTextfield_vide3==true){
            jTextField3.setForeground(new java.awt.Color(0,0,0));
            jTextField3.setText("");
            jTextfield_vide3=false;
        }
    }//GEN-LAST:event_jTextField3MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        if (choix_suppression==false){
            jLabel14.setBackground(new Color(52, 82, 104));
            jLabel17.setBackground(new Color(250, 0, 0));
            jLabel4.setBackground(new Color(250,0,0));
            //jLabel4.setBackground(new Color(250,0,0));
            //jLabel6.setBackground(new Color(250,0,0));
            jLabel9.setBackground(new Color(250,0,0));
            jLabel21.setVisible(false);
        jTextField9.setVisible(false);
        jButton3.setVisible(false);
        jLabel11.setVisible(false);
        jLabel10.setVisible(false);
        jTextField2.setVisible(false);
        jLabel12.setVisible(false);
        jTextField3.setVisible(false);
        jLabel13.setVisible(false);
        jTextField4.setVisible(false);
       
        jButton6.setVisible(false);
        jButton7.setVisible(false);
        jButton8.setVisible(false);
        jLabel31.setVisible(false);
        jButton9.setVisible(false);
        jButton13.setVisible(false);
        jLabel32.setVisible(false);
        jTextField18.setVisible(false);
        jButton11.setVisible(false);
        jButton10.setVisible(false);
        jLabel33.setVisible(false);
        jTextField19.setVisible(false);
        jLabel34.setVisible(false);
        jComboBox1.setVisible(false);
	jButton12.setVisible(false);
        jButton13.setVisible(false);

        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jTextField1.setVisible(false);
        jButton10.setVisible(false);
        jComboBox2.setVisible(false);
            jLabel6.setVisible(false);
        jButton1.setVisible(false);
        jLabel20.setVisible(false);
        jButton4.setVisible(false);
        jLabel16.setVisible(true);
        jButton2.setVisible(true);
        jTextField9.setVisible(true);
        jButton5.setVisible(false);
        jLabel18.setVisible(false);
        jScrollPane1.setVisible(false);
        jTable1.setVisible(false);
        }
        
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        jLabel20.setVisible(false);
        jButton5.setVisible(false);
        jButton4.setVisible(false);
        jLabel16.setVisible(true);
        jTextField9.setVisible(true);
        jButton2.setVisible(true);
        
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        String codete=jTextField9.getText();
        if (codete.equals("")){
            jTextfield_vide9=true;
            jTextField9.setForeground(Color.RED);
            jTextField9.setText("Veuiller entrer le code");
        }
      if (!codete.equals("") && jTextfield_vide9==false){
        jLabel16.setVisible(false);
        jTextField9.setVisible(false);
        jButton2.setVisible(false);
        connector_utilisateur conn=new connector_utilisateur();
        String codet=jTextField9.getText();
        int code=getStringToInt(codet);
        String etat="";
        try {
            etat = conn.setSupprimerCompte(code);
        } catch (SQLException ex) {
            Logger.getLogger(Gestiondescomptes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Gestiondescomptes.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (etat.equals("succes")){
            jLabel20.setText("Compte supprimer avec succès!");
            jLabel20.setVisible(true);
            jButton4.setVisible(true);
            
        }
        
         if (etat.equals("echec")){
            jLabel20.setText("Compte non supprimer!");
            jLabel20.setVisible(true);
            jButton4.setVisible(true);
         }
      }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseEntered

    private void jComboBox2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MouseMoved
        // TODO add your handling code here:
        jComboBox1.removeAll();
        jComboBox1.addItem("Courant");
        jComboBox1.addItem("Epargne");
    }//GEN-LAST:event_jComboBox2MouseMoved

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
        jLabel17.setBackground(new Color(52, 82, 104));
        jLabel14.setBackground(new Color(250, 0, 0));
            jLabel4.setBackground(new Color(250,0,0));
            //jLabel4.setBackground(new Color(250,0,0));
            //jLabel6.setBackground(new Color(250,0,0));
            jLabel9.setBackground(new Color(250,0,0));
            jLabel21.setVisible(false);
        jTextField9.setVisible(false);
        jButton3.setVisible(false);
        jLabel11.setVisible(false);
        jLabel10.setVisible(false);
        jTextField2.setVisible(false);
        jLabel12.setVisible(false);
        jTextField3.setVisible(false);
        jLabel13.setVisible(false);
        jTextField4.setVisible(false);
       
        jButton6.setVisible(false);
        jButton7.setVisible(false);
        jButton8.setVisible(false);
        jLabel31.setVisible(false);
        jButton9.setVisible(false);
        jButton13.setVisible(false);
        jLabel32.setVisible(false);
        jTextField18.setVisible(false);
        jButton11.setVisible(false);
        jButton10.setVisible(false);
        jLabel33.setVisible(false);
        jTextField19.setVisible(false);
        jLabel34.setVisible(false);
        jComboBox1.setVisible(false);
	jButton12.setVisible(false);
        jButton13.setVisible(false);

        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jTextField1.setVisible(false);
        jButton10.setVisible(false);
        jComboBox2.setVisible(false);
            jLabel6.setVisible(false);
        jButton1.setVisible(false);
        jLabel20.setVisible(false);
        jButton4.setVisible(false);
        jLabel16.setVisible(true);
        jButton2.setVisible(false);
        jTextField9.setVisible(true);
        jButton5.setVisible(true);
        jLabel18.setVisible(false);
        jScrollPane1.setVisible(true);
        jTable1.setVisible(true);
        
    }//GEN-LAST:event_jLabel17MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestiondescomptes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestiondescomptes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestiondescomptes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestiondescomptes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestiondescomptes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
